### ISSUE TITLE
example.xcodeproj doesn't build

### ISSUE THREAD

**Issue by erikras** [magus/react-native-facebook-login#10]
Gives:

`'RCTBridge.h' file not found` on `RCTFBLoginManager.m:3`
`'RCTView.h' file not found` on `RCTFBLogin.h:1`

I'm having the same problem when I try to follow the instructions on my own project.

**Comment by magus** [comment]
Can you share your package.json? Also did you run npm install in the example directory?

**Comment by erikras** [comment]
I did get the example project to build and run after doing `npm install`, but my project that I've pieced together from scratch using the instructions does not. There's not much to glean from the package.json, I'm afraid.
```
{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "react-native": "^0.4.0",
    "react-native-facebook-login": "^0.4.3"
  }
}
```
I still get the exact errors shown above. Any other ideas?

**Comment by erikras** [comment]
Ugh, now the example, freshly unzipped, is failing. :-(

**Comment by erikras** [comment]
Closing and reopening Xcode fixed the example project, but not my own.

**Comment by magus** [comment]
I have a feeling it may be a configuration issue. Have you tried creating a new React native project, adding the login button and building? The more code you can share the better

**Comment by erikras** [comment]
[Here's a zip of a brand new project](https://dl.dropboxusercontent.com/u/5100577/MyApp.zip) (30.3 MB). Steps to recreate:

1. `react-native init MyApp`
2. `cd MyApp`
3. `npm install --save react-native-facebook-login`
4. `open MyApp.xcodeproj`
5. Drag `node_modules/react-native-facebook-login/RCTFBLogin.xcodeproj` into the project.
6. Drag `node_modules/react-native-facebook-login/FacebookSDK/*` into the project. (I've tried with a fresh download from FB, too) At this point, it all still compiles.
7. Add `libRCTFBLogin.a` into the `Link Binary With Libraries` Build Phase.
8. Project no longer builds. `'RCTView.h' file not found`

I stopped short of editing the `Info.plist` or the `AppDelegate.m` because it doesn't seem like that's going to fix the build problem.

**Comment by magus** [comment]
Thanks for the steps @erikras, found the bug and will have the fix pushed shortly!

**Comment by erikras** [comment]
Awesome! :+1:

**Comment by magus** [comment]
`npm install --save react-native-facebook-login@0.4.5` should fix you up!

**Comment by billybil** [comment]
Hell @magus I'm also getting this error and have no idea how to resolve, my steps to repro are pretty much the same as @erikras. Please advise?

**Comment by billybil** [comment]
actually I updated the header search paths and added "$(PROJECT_DIR)/node_modules/react-native/React/**" that seems to have fixed it

**Comment by magus** [comment]
This issue was regressed with a recent change I made.

**Comment by csw244** [comment]
I seem to have the same issue. Is this fixed?

**Comment by magus** [comment]
Can you post a screenshot or copy of the error along with your project code?

**Comment by magus** [comment]
Feel free to open a new issue with your details Stephanie.
