### ISSUE TITLE
FBLoginManager.loginWithPermissions (..) - loginBehaviour?

### ISSUE THREAD

**Issue by skizzo** [magus/react-native-facebook-login#103]
Is there any way to set the desired l[ogin behaviour](https://github.com/magus/react-native-facebook-login#login-behavior) when not using the [FBLogin](https://github.com/magus/react-native-facebook-login#fblogin) button but [FBLoginManager](https://github.com/magus/react-native-facebook-login#fbloginmanager)? Would be really great, since FBLogin doesn't allow too much styling. Thanks!

**Comment by jamesone** [comment]
Have you found out how to do this yet? @skizzo I'm in the same boat. BH

**Comment by skizzo** [comment]
nope, unfortunately not..

**Comment by lwhiteley** [comment]
can someone here volunteer to test the mentioned PR
and see if this issue is properly resolved for Android

Please continue the conversation in the Pull Request 

https://github.com/magus/react-native-facebook-login/pull/105

[install from my fork directly to test (using github url)]

**Comment by lwhiteley** [comment]
This issue should now be resolved 
#130
