### ISSUE TITLE
Facebook Logout not ending off facebook session

### ISSUE THREAD

**Issue by prabakarviji** [magus/react-native-facebook-login#107]
I am able to login into facebook successfully.While clicking logout button it shwoing logout message and navigate to login Button page.But when again logging it show authorization page instead login page

**Comment by lwhiteley** [comment]
android or IOS?

**Comment by prabakarviji** [comment]
iOS RN Version 0.19

**Comment by lwhiteley** [comment]
@magus this seems to be something for you as im not familiar with the IOS side of things

**Comment by prabakarviji** [comment]
Here i mentioned SOF to further reference
[http://stackoverflow.com/questions/32064431/facebook-doesnt-logout-completely-ios](url)

**Comment by magus** [comment]
This is the expected behavior of the button. Once you've authorized the app the permissions are set. In order to see the authorization page again you'd need to delete the app from your settings in Facebook.

**Comment by prabakarviji** [comment]
Thanks @magus

**Comment by Blutude** [comment]
What if I want to login with facebook but with another email? Is there no way to logout of the account completely? Or switch accounts?
