### ISSUE TITLE
Change login behaviour using FBLoginMock

### ISSUE THREAD

**Issue by mfuruskog** [magus/react-native-facebook-login#113]
Is it possible to change the login behaviour to native when using a solution based on FBLoginMock? Currently the button will only open Facebook within the browser, even though Facebook is installed on the device.

**Comment by mfuruskog** [comment]
Maybe I should rephrase the question: is it possible to change the behaviour when only using FBLoginManager and not FBLogin? Both for Android and iOS.

**Comment by lwhiteley** [comment]
for android this feature is in a PR waiting to be merged 

#105 
you can test it there

IOS should follow as well.

**Comment by lwhiteley** [comment]
just to note that this issue is similar to issue #103

**Comment by lwhiteley** [comment]
this should now be possible with the inclusion of #130
