### ISSUE TITLE
support for RN 0.26

### ISSUE THREAD

**Issue by sodik82** [magus/react-native-facebook-login#115]
it would be great if you can release new version with support for RN 0.26 and resolve the deprecations from RN 0.25 (see https://github.com/facebook/react-native/releases/tag/v0.25.1)

Possible solution https://github.com/cridenour/react-native-facebook-login/commit/b2ba56b8791d9d75cd674f35caf7bd77ef059dcf

**Comment by lwhiteley** [comment]
version 1.2.0 released
