### ISSUE TITLE
undefined is not an object (evaluating 'PropTypes.array')

### ISSUE THREAD

**Issue by letthewookieewin** [magus/react-native-facebook-login#118]
I'm getting this error on import - I'm running react-native 0.26 (I have another project running react-native 0.25 where I didn't run into this issue)

**Comment by lwhiteley** [comment]
that may be because of the depracations for migrating to that version..

point to the master repo in your npm package and run npm update.. the fix should be there for now

https://github.com/magus/react-native-facebook-login

we have not published to npm as yet

**Comment by sodik82** [comment]
any chance to release just this fix as patch release any soon? should be safe enough.

**Comment by lwhiteley** [comment]
version 1.2.0 released
