### ISSUE TITLE
Weird crash on FBLoginManager.Events only when not in debugging mode

### ISSUE THREAD

**Issue by BigPun86** [magus/react-native-facebook-login#119]
Hey there!

I am facing a weird issue accoriding this module. When i try to run my app with FBLogin module it crashes with this error message:

<img width="315" alt="screen shot 2016-05-22 at 19 49 10" src="https://cloud.githubusercontent.com/assets/7880624/15455509/4771dd6a-2056-11e6-8762-200de07e140d.png">

Now the weird thing is, that when i am in debug mode, than this works great....Any ideas how to solve this ?!

**Comment by lwhiteley** [comment]
see if issue #110 helps

**Comment by BigPun86** [comment]
Great! Worked fine, thanks @lwhiteley
