### ISSUE TITLE
How to make Graph Requests

### ISSUE THREAD

**Issue by vinceprofeta** [magus/react-native-facebook-login#127]
Are there exposed methods to make Facebook graph requests once the login flow is setup? What is the best way to do this?

**Comment by lwhiteley** [comment]
either import a lib or you can take a look at the example 

https://github.com/magus/react-native-facebook-login/blob/master/example/components/LoginMock.js#L80-L96


it is not currently exposed

**Comment by vinceprofeta** [comment]
@lwhiteley, Awesome, thanks! Do you have any recommended libraries?

**Comment by lwhiteley** [comment]
i havent had a use case for it actually so i don't have a recommended one.

heres one you may try https://www.npmjs.com/package/fbgraph (not sure if it works for RN though)

or you can try out fbsdk https://github.com/facebook/react-native-fbsdk

not sure how far they went with it yet, been out of sync with progress
