### ISSUE TITLE
Graph API v2.1 Upgrade Notice

### ISSUE THREAD

**Issue by leoabacade** [magus/react-native-facebook-login#129]
<img width="830" alt="screen shot 2016-07-08 at 4 59 17 pm" src="https://cloud.githubusercontent.com/assets/2664504/16682530/9da891b4-452d-11e6-8389-be0a99c30233.png">

has anyone received this notice on Facebook developer before?

"name": "react-native-facebook-login",
 "version": "1.0.3",

**Comment by lwhiteley** [comment]
is there a reason you are not using the latest version?

**Comment by lwhiteley** [comment]
closing due to no answer
