### ISSUE TITLE
RN 0.30.0 - FacebookLoginModule is not abstract and does not override abstract method onNewIntent(Intent) in ActivityEventListener

### ISSUE THREAD

**Issue by yonahforst** [magus/react-native-facebook-login#131]
Trying to install on android and gradle build throws this error:
```
:react-native-facebook-login:processReleaseResources
:react-native-facebook-login:generateReleaseSources
:react-native-facebook-login:incrementalReleaseJavaCompilationSafeguard
:react-native-facebook-login:compileReleaseJavaWithJavac
:react-native-facebook-login:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/Yonah/development/react/proximator/node_modules/react-native-facebook-login/android/src/main/java/com/magus/fblogin/FacebookLoginModule.java
Error:(37, 8) error: FacebookLoginModule is not abstract and does not override abstract method onNewIntent(Intent) in ActivityEventListener
:react-native-facebook-login:compileReleaseJavaWithJavac FAILED
Error:Execution failed for task ':react-native-facebook-login:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

adding
```java
    public void onNewIntent(Intent intent) {

    }
```
to the end of `FacebookLoginModule.java` seems to fix the problem. Will submit a PR once confirmed

**Comment by Arkanine** [comment]
I have the same issue after updating to react-native 0.33.
Also I already have 
public void onNewIntent(Intent intent) { 
} 
in FacebookLoginModule.java

**Comment by waleedarshad-vf** [comment]
Same issue facing after upgrading to react-native 0.3.3

**Comment by waleedarshad-vf** [comment]
+1

**Comment by lwhiteley** [comment]
please make sure you are running the latest version of this module.

im pretty sure this method is there 2 releases ago.

update the module and try again 

and continue the conversation in issue #160

**Comment by waleedarshad-vf** [comment]
@lwhiteley after getting latest version although build get install but just get crashed :(

**Comment by lwhiteley** [comment]
Steps:
- run `adb logcat ` (This will start the android log for you to see)
- run the app  again and let it crash
- if its still related to this module then create a new issue so we can track this specifically

Thanks @waleedarshad-vf
