### ISSUE TITLE
App crashes after React-Native Update

### ISSUE THREAD

**Issue by BigPun86** [magus/react-native-facebook-login#134]
Hey there, i am now using React-Native 29.2 and facebook-login 1.2.0

Since i have processed the update my app crashes as soon as i try to call the FBLogin:

````
E  FATAL EXCEPTION: main
E  Process: com.mobileemotion.camigo, PID: 2681
E  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
E      at com.facebook.login.LoginClient.getLogger(LoginClient.java:367)
E      at com.facebook.login.LoginClient.logAuthorizationMethodComplete(LoginClient.java:417)
E      at com.facebook.login.LoginClient.tryNextHandler(LoginClient.java:200)
E      at com.facebook.login.GetTokenLoginMethodHandler.getTokenCompleted(GetTokenLoginMethodHandler.java:119)
E      at com.facebook.login.GetTokenLoginMethodHandler$1.completed(GetTokenLoginMethodHandler.java:74)
E      at com.facebook.internal.PlatformServiceClient.callback(PlatformServiceClient.java:157)
E      at com.facebook.internal.PlatformServiceClient.handleMessage(PlatformServiceClient.java:141)
E      at com.facebook.internal.PlatformServiceClient$1.handleMessage(PlatformServiceClient.java:62)
E      at android.os.Handler.dispatchMessage(Handler.java:102)
E      at android.os.Looper.loop(Looper.java:135)
E      at android.app.ActivityThread.main(ActivityThread.java:5254)
E      at java.lang.reflect.Method.invoke(Native Method)
E      at java.lang.reflect.Method.invoke(Method.java:372)
E      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
````

My Crashlytics reports me that the crash is in 

    LoginClient.java line 367 com.facebook.login.LoginClient.getLogger

**Comment by BigPun86** [comment]
I really don´t know why, but after updateing my build gradle from 
        
        classpath 'com.android.tools.build:gradle:1.3.1'

to

        classpath 'com.android.tools.build:gradle:2.1.2'

and rebuilding, everything works fine 

Any ideas how this is related?

**Comment by lwhiteley** [comment]
could be that the fb sdk is using a newer version of the gradle build tools for something specific. 
by relation that would be my only conclusion from what you say.

if you downgrade, does it break again?

**Comment by BigPun86** [comment]
Nope, that wasn´t the issue...I have reverted everything, and now it still works :P Sorry, but i can´t reproduce the error.

**Comment by BigPun86** [comment]
close

**Comment by lwhiteley** [comment]
cool no prob

**Comment by cashweaver** [comment]
I just encountered this exact error and solved it by walking through the [Android setup](https://github.com/magus/react-native-facebook-login/blob/master/android/README.md) for this module. I was missing the string resources and a few lines in the manifest.

Hope this helps anyone who encounters this error in the future!
