### ISSUE TITLE
Different login behavior on iOS 9 and iOS 8

### ISSUE THREAD

**Issue by ssmlee04** [magus/react-native-facebook-login#140]
For the same build, for iOS 9 the Facebook login would open a browser and let user enter the email and password. However on iOS 8 it just opens my Facebook app and reads some info and login directly. Wondering why is it different and is there a way I can open an app instead of opening a browser on iOS 9?

p.s: I have my Facebook app installed on both devices.

**Comment by lwhiteley** [comment]
this happens even when you specify the login behaviour?

**Comment by ssmlee04** [comment]
ya even if I specify `loginBehavior ={FBLoginManager.LoginBehaviors.Native}` It still opens a browser.

**Comment by lwhiteley** [comment]
interesting, I've never actually used the IOS side so I wouldn't be able to help.. just letting you confirm some more context. @magus or someone in the community could be better help

**Comment by ssmlee04** [comment]
btw the iOS SDK is 4.13.1. don't know if that matters though.

**Comment by lwhiteley** [comment]
maybe, it does sound sdk/platform related .. you can prob try different versions to debug

**Comment by ssmlee04** [comment]
[https://developers.facebook.com/bugs/786729821439894/?search_id](https://developers.facebook.com/bugs/786729821439894/?search_id)

it appears this behavior on iOS 9 is by design... this just don't make sense..

**Comment by lwhiteley** [comment]
interesting stuff 

closing due to issue being out of scope
