### ISSUE TITLE
After login not back in App

### ISSUE THREAD

**Issue by uc-asa** [magus/react-native-facebook-login#143]
Hello Team,

I'm using react-native-facebook-login but after  in facebook.com unable to return in my app and get callback data

**Comment by lwhiteley** [comment]
RN version?
platform?
module version?

**Comment by uc-asa** [comment]
Hello team,

I have corrected this problem actual I was missed info.plist updation so this error was occur

**Comment by lwhiteley** [comment]
ok good to know
