### ISSUE TITLE
undefined is not an object (evaluating 'FBLoginManagerl.loginWithPermissions')

### ISSUE THREAD

**Issue by somu321** [magus/react-native-facebook-login#149]
i am facing the  error " undefined is not an object" when i am using the below example:

import React, { PropTypes, Component } from 'react';
var {FBLogin, FBLoginManager} = require('react-native-facebook-login');

class Login extends Component {
  render() {
    return (
     ` <FBLogin />  ` 
    );
  }
};

**Comment by lwhiteley** [comment]
`FBLoginManagerl`? if you copied this directly from the error message then you should be getting an error. 

Dont have enough context either as to where this is happening and which platform.

but check if the variable is mispelled somewhere.

should be 
`FBLoginManager.loginWithPermissions`

and not 

`FBLoginManagerl.loginWithPermissions`

**Comment by somu321** [comment]
typo mistake. i got error  "undefined is not an object (evaluating 'FBLoginManager.loginWithPermissions')"  when we click on the facebook button

platform : android

**Comment by lwhiteley** [comment]
did you follow the android setup guide step by step?

https://github.com/magus/react-native-facebook-login/tree/master/android

if you dont setup the gradle and java class side of things properly then the component wont be registered in the react ecosystem

**Comment by somu321** [comment]
yes ,followed setup guide correctly

**Comment by lwhiteley** [comment]
try to change this statement
`var {FBLogin, FBLoginManager} = require('react-native-facebook-login');`

to 

`import  {FBLogin, FBLoginManager} from 'react-native-facebook-login'`

just a hunch but dont see why it would be important. 

also if that doesnt work is it possible for you to post snippets of your full setup .. just the parts regarding this library

**Comment by somu321** [comment]
now i am facing the error  "unfortunately app has stopped and below is the logcat


Caused by: java.lang.IllegalAccessError: Method 'void android.support.v4.net.ConnectivityManagerCompat.<init>()' is inaccessible to class 'com.facebook.react.modules.netinfo.NetInfoModule' (declaration of 'com.facebook.react.modules.netinfo.NetInfoModule' appears in /data/app/com.folinknative-1/base.apk

**Comment by lwhiteley** [comment]
what permissions are in your androidmanifest?

**Comment by somu321** [comment]
<uses-permission android:name="android.permission.INTERNET" />

**Comment by lwhiteley** [comment]
try adding this as well:

`<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />`

**Comment by lwhiteley** [comment]
https://github.com/facebook/react-native/issues/6152

seems others are facing that error as well.. you can read through here

**Comment by somu321** [comment]
thanks for the support

**Comment by lwhiteley** [comment]
were you able to get it resolved?

**Comment by somu321** [comment]
updated react native  from 0.20 to 0.31 and installed android support repository in andriod SDK manager

**Comment by lwhiteley** [comment]
ok awesome .. good to know its working now

**Comment by bennygenel** [comment]
I am having the same issue on Android. 

Followed the Android install guide. Did everything but still having the error. No problem with iOS. Same code working just fine.

```
"react-native": "0.39.2",
"react-native-facebook-login": "^1.4.0",
"react-native-fbsdk": "^0.4.0",
```

**undefined is not an object (evaluating 'FBLoginManager.Events["LoginFound"]')**

Any suggestions to solve this issue?

**Comment by BigPun86** [comment]
+1 Same issue here

**Comment by dittmarconsulting** [comment]
"react": "16.0.0-alpha.6",
"react-native": "0.43.3",
"react-native-fbsdk": "^0.5.0"

I get the same red screen on Android. Mind due it works fine in iOS.

```
LoginManager.logInWithReadPermissions(['public_profile'])
   .then(result => {
   }
```

![screenshot 2017-05-19 17 46 22](https://cloud.githubusercontent.com/assets/19203201/26238170/49fbe10c-3cbb-11e7-95ca-670f0677cafc.png)
