### ISSUE TITLE
The example app doesnt redirect back to application from safari browser

### ISSUE THREAD

**Issue by agenthunt** [magus/react-native-facebook-login#15]
The example app doesnt redirect back to application from safari browser. Any thoughts ?

**Comment by magus** [comment]
Can you share your package.json with me? :)

**Comment by magus** [comment]
Hm I can't seem to repro, can you share your package.json? Did you make any changes? What version of react-native?

**Comment by agenthunt** [comment]
Sorry, I had the app id twice in the URL schemes.  Thanks.

**Comment by magus** [comment]
I just updated to react-native 0.6.0 and everything seems to be working as intended still! Feel free to update the latest version it'll be on npm in a few moments.

Going to close this out, thanks for using it! Cheers :+1:
