### ISSUE TITLE
Is Facebook share option available for android?

### ISSUE THREAD

**Issue by sudharsan1988** [magus/react-native-facebook-login#150]
As we are using fbsdk, does the Facebook share option available for android? For example, if we want to share a custom title, description, image link to FB, is it supported in this module? Login feature is working great and Readme is very clear enough to set things up easily. Many thanks for this awesome module.

**Comment by lwhiteley** [comment]
hey thanks for the positive feedback but share wasn't the goal of the module and we didnt push much efforts to get it in.

There are a couple options and using https://github.com/facebook/react-native-fbsdk is one of them. It is a full featured fbsdk from the facebook team. 

personally, i havent used it on a project as yet so i cant be sure what the gotchas are. 

There is a PR (#66 ) as well for our repository that may give you ideas if you want to include it as well

**Comment by sudharsan1988** [comment]
Yes, I used fbsdk for the share option and that worked great. Thank you for your help. Please close this issue.

**Comment by lwhiteley** [comment]
ok sounds good, glad you got through
