### ISSUE TITLE
Getting react-native-fbsdk LoginManager object when remote debugging disabled?

### ISSUE THREAD

**Issue by teepark** [magus/react-native-facebook-login#151]
This is so strange. In one file I have:

```javascript
import {
  GraphRequest,
  GraphRequestManager,
} from 'react-native-fbsdk'

import { FBLoginManager } from 'react-native-facebook-login'

console.log("FBLoginManager:", FBLoginManager)
```

(I need both because I make graph API requests, but also want the token-caching behavior of `react-native-facebook-login`)

When I run the app with *remote debugging* turned on, the app works fine and the log shows me what I expect to see:

```
FBLoginManager: Object { Events: Object, LoginBehaviors: Object}
    Events: Object
    LoginBehaviors: Object
    getCredentials: fn()
    login: fn()
    loginWithPermissions: fn()
    logout: fn()
    setLoginBehavior: fn()
    __proto__: Object
```

But if I turn off remote debugging, it shows me the methods of the `LoginManager` from `react-native-fbsdk`:

```
'FBLoginManager:', { setLoginBehavior: { [Function: fn] type: 'remote' },
  setDefaultAudience: { [Function: fn] type: 'remote' },
  getLoginBehavior: { [Function: fn] type: 'remoteAsync' },
  getDefaultAudience: { [Function: fn] type: 'remoteAsync' },
  logInWithReadPermissions: { [Function: fn] type: 'remoteAsync' },
  logInWithPublishPermissions: { [Function: fn] type: 'remoteAsync' },
  logOut: { [Function: fn] type: 'remote' } }
```

And of course production builds are broken, having the same wrong login manager object as dev builds without remote debugging.

I have no idea why it would be exposing the wrong object, or especially why it would be gated on remote debugging, but I can reliably reproduce these behaviors.

EDIT: this is on iOS

**Comment by lwhiteley** [comment]
interesting.. might be because the name is the same and it is clashing

**Comment by teepark** [comment]
almost. in `react-native-fbsdk` the object is named [`LoginManager`](https://developers.facebook.com/docs/react-native/login).

**Comment by lwhiteley** [comment]
oh ill have to look at the code to isolate it, do you ever use their LoginManager in your code?

**Comment by teepark** [comment]
No, I recently removed it in favor of the `FBLoginManager` from this package.

**Comment by lwhiteley** [comment]
are you using android/ios/both?

**Comment by lwhiteley** [comment]
but its as I suspected for android

https://github.com/facebook/react-native-fbsdk/blob/master/android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginManagerModule.java#L85

The module name in the background is the same

**Comment by teepark** [comment]
in my case I'm on iOS.

**Comment by lwhiteley** [comment]
usually its a unified name but just to make it a little clearer. 

heres another snippet from their code. 

They change the variable ref for the end user but the component is named "FBLoginManager" in the background for IOS as well

https://github.com/facebook/react-native-fbsdk/blob/eea514d8edc8e66f087891aeeb7dde2d5fb0b68d/js/FBLoginManager.js#L24

So some wires being crossed here.

**Comment by lwhiteley** [comment]
so next steps from here since this is a third party module is to namespace our `FBLoginManager` to possibly `MFBLoginManager`

if you want to get ahead of me or @magus,  you can submit a working PR if possible 👍  :)
