### ISSUE TITLE
Android failed to login on Release

### ISSUE THREAD

**Issue by ssmlee04** [magus/react-native-facebook-login#153]
I have setup the Android Facebook login with your instructions and I have no problem logging in with the login SDK in development environment. 

However, when I am trying to bundle the code and run in release mode, the Facebook login functionality stops working.  

The following is the things that I do: 
https://facebook.github.io/react-native/docs/signed-apk-android.html

When I click on "Login with Facebook" it opens a blank page with a loading image, waits for 1 second and goes back to the same screen like nothing happened. Since it is in release mode I don't know how to proceed and debug this.

Does anyone know what is happening? Thanks.

**Comment by lwhiteley** [comment]
posting logs from logcat would be helpful

**Comment by ssmlee04** [comment]
I have located the problem by doing `react-native run-android --variant=debug` and from the console I can see that I do not have a valid Key Hash for my release build. So that is the problem.
