### ISSUE TITLE
FacebookLoginModule is not abstract and does not override abstract method onActivityResult(Activity,int,int,Intent) in ActivityEventListener

### ISSUE THREAD

**Issue by ivesy85** [magus/react-native-facebook-login#158]
I am getting this error in react native 0.33

:react-native-facebook-login:compileReleaseJavaWithJavac
/Applications/XAMPP/xamppfiles/htdocs/testRN033/node_modules/react-native-facebook-login/android/src/main/java/com/magus/fblogin/FacebookLoginModule.java:37: error: FacebookLoginModule is not abstract and does not override abstract method onActivityResult(Activity,int,int,Intent) in ActivityEventListener
public class FacebookLoginModule extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
1 error
:react-native-facebook-login:compileReleaseJavaWithJavac FAILED

**Comment by lwhiteley** [comment]
new release published
