### ISSUE TITLE
Error on build FacebookLoginModule is not abstract and does not override abstract method onActivityResult

### ISSUE THREAD

**Issue by avalla** [magus/react-native-facebook-login#160]
Hello, 
I cannot build the android version, I followed instructions but I receive this error

$ react-native run-android
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug...
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:react-native-facebook-login:compileLint
:react-native-facebook-login:copyReleaseLint UP-TO-DATE
:react-native-facebook-login:preBuild UP-TO-DATE
:react-native-facebook-login:preReleaseBuild UP-TO-DATE
:react-native-facebook-login:checkReleaseManifest
:react-native-facebook-login:preDebugAndroidTestBuild UP-TO-DATE
:react-native-facebook-login:preDebugBuild UP-TO-DATE
:react-native-facebook-login:preDebugUnitTestBuild UP-TO-DATE
:react-native-facebook-login:preReleaseUnitTestBuild UP-TO-DATE
:react-native-facebook-login:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:react-native-facebook-login:prepareComAndroidSupportCardviewV72320Library UP-TO-DATE
:react-native-facebook-login:prepareComAndroidSupportRecyclerviewV72301Library UP-TO-DATE
:react-native-facebook-login:prepareComAndroidSupportSupportV42321Library UP-TO-DATE
:react-native-facebook-login:prepareComFacebookAndroidFacebookAndroidSdk4101Library UP-TO-DATE
:react-native-facebook-login:prepareComFacebookFrescoDrawee0110Library UP-TO-DATE
:react-native-facebook-login:prepareComFacebookFrescoFbcore0110Library UP-TO-DATE
:react-native-facebook-login:prepareComFacebookFrescoFresco0110Library UP-TO-DATE
:react-native-facebook-login:prepareComFacebookFrescoImagepipeline0110Library UP-TO-DATE
:react-native-facebook-login:prepareComFacebookFrescoImagepipelineBase0110Library UP-TO-DATE
:react-native-facebook-login:prepareComFacebookFrescoImagepipelineOkhttp30110Library UP-TO-DATE
:react-native-facebook-login:prepareComFacebookReactReactNative0330Library UP-TO-DATE
:react-native-facebook-login:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:react-native-facebook-login:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:react-native-facebook-login:prepareReleaseDependencies
:react-native-facebook-login:compileReleaseAidl UP-TO-DATE
:react-native-facebook-login:compileReleaseRenderscript UP-TO-DATE
:react-native-facebook-login:generateReleaseBuildConfig UP-TO-DATE
:react-native-facebook-login:generateReleaseAssets UP-TO-DATE
:react-native-facebook-login:mergeReleaseAssets UP-TO-DATE
:react-native-facebook-login:generateReleaseResValues UP-TO-DATE
:react-native-facebook-login:generateReleaseResources UP-TO-DATE
:react-native-facebook-login:mergeReleaseResources UP-TO-DATE
:react-native-facebook-login:processReleaseManifest UP-TO-DATE
:react-native-facebook-login:processReleaseResources UP-TO-DATE
:react-native-facebook-login:generateReleaseSources UP-TO-DATE
:react-native-facebook-login:processReleaseJavaRes UP-TO-DATE
:react-native-facebook-login:compileReleaseJavaWithJavac
/Users/andrea/dev/react-native/AuthTest/node_modules/react-native-facebook-login/android/src/main/java/com/magus/fblogin/FacebookLoginModule.java:37: error: FacebookLoginModule is not abstract and does not override abstract method onActivityResult(Activity,int,int,Intent) in ActivityEventListener
public class FacebookLoginModule extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
1 error
:react-native-facebook-login:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-facebook-login:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 8.066 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

Thanks and best regards!!

**Comment by lwhiteley** [comment]
just fixed this but is not published yet similar to issue #158 

please ref master for now until deployed.. let me know if it works

**Comment by avalla** [comment]
it works :)

Thanks, I'm sorry for duplicated issue :)

**Comment by lwhiteley** [comment]
new release published
