### ISSUE TITLE
override abstract method onActivityResult

### ISSUE THREAD

**Issue by Stereobit** [magus/react-native-facebook-login#161]
Hi, I'm running into the following issue whilebuilding the Android version: ```Error:(37, 8) error: FacebookLoginModule is not abstract and does not override abstract method onActivityResult(Activity,int,int,Intent) in ActivityEventListener```

Overwriting the abstract method  helps but I'm not sure if this is the right way?

**Comment by lwhiteley** [comment]
please use master until latest code is released

similar to #158 and #160

**Comment by Stereobit** [comment]
Works. Thanks a lot :)

**Comment by lwhiteley** [comment]
new release published
