### ISSUE TITLE
AppState module trying to override native AppState module

### ISSUE THREAD

**Issue by manjeet-dobble** [magus/react-native-facebook-login#163]
As soon as I install this library and done all the setup I get following error while running on the android device - "Appstate module trying to override native AppStateModule " .... so I removed the library and my project working fine, but I wanted to use this library , so please check what went wrong

**Comment by lwhiteley** [comment]
The only android dependencies this imports is facebook-android-sdk and react-native, 
not sure why you would be getting that error.

unfortunately you will have to let me know how to reproduce this error. This is a very unique case.

for eg which other libs are you using and compiling with  gradle etc.

also try to clean before you build

`cd android && ./gradlew clean && cd ..`

**Comment by manjeet-dobble** [comment]
Libraries used by me in build.gradle as dependencies are  
1)react-native-vector-icons
2)react-native-share
3)react-native-contacts

-I will try clean option and will let you know soon

**Comment by lwhiteley** [comment]
k also please make sure you are running the latest version of this module. thanks

**Comment by lwhiteley** [comment]
I am working on a personal app with all these dependencies you mentioned and ive never seen this issue once. not sure why you're getting that still.

can you post the error as you see in int he console?

**Comment by manjeet-dobble** [comment]
tried today and its working fine now, don't know why it was producing that error in the past
