### ISSUE TITLE
RN 0.33.0 - FacebookLoginModule is not abstract and does not override abstract method onNewIntent(Intent) in ActivityEventListener

### ISSUE THREAD

**Issue by Arkanine** [magus/react-native-facebook-login#164]
I run into this error
:react-native-facebook-login:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/roman/Work/TheUpperRoom/node_modules/react-native-facebook-login/android/src/main/java/com/magus/fblogin/FacebookLoginModule.java:37: error: FacebookLoginModule is not abstract and does not override abstract method onNewIntent(Intent) in ActivityEventListener
public class FacebookLoginModule extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
1 error
:react-native-facebook-login:compileReleaseJavaWithJavac FAILED

after updating to react-native 0.33.
Also I already have 
public void onNewIntent(Intent intent) { 
} 
in FacebookLoginModule.java, as mentioned there

https://github.com/magus/react-native-facebook-login/issues/131

**Comment by lwhiteley** [comment]
please make sure you are running the latest version of this module.

im pretty sure this method is there 2 releases ago.

update the module and try again

**Comment by Arkanine** [comment]
@lwhiteley you right, my version of react-native-facebook-login was 1.3.0. After updating looks like module works fine, thank you!

**Comment by lwhiteley** [comment]
closing due to issue being resolved.
