### ISSUE TITLE
Android build fails on RN 0.34

### ISSUE THREAD

**Issue by sznrbrt** [magus/react-native-facebook-login#168]
**After upgrading to RN 0.34 Android build fails**

## Version 
    "react-native": "0.34.0" 

## Error
/node_modules/react-native-facebook-login/android/src/main/java/com/magus/fblogin/FacebookLoginModule.java:37: error: FacebookLoginModule is not abstract and does not override abstract method onActivityResult(Activity,int,int,Intent) in ActivityEventListener
public class FacebookLoginModule extends ReactContextBaseJavaModule implements ActivityEventListener {
       ^
1 error
:react-native-facebook-login:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-facebook-login:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by lwhiteley** [comment]
this was reported and resolved a long time ago.
 please get the latest version of this module

similar to #164 #160

**Comment by sznrbrt** [comment]
That's embarrassing...😅 Thank You!
