### ISSUE TITLE
App crashes when clicking login

### ISSUE THREAD

**Issue by lwhiteley** [magus/react-native-facebook-login#169]
@saeed2402 

Thanks again. I started with a fresh project and followed the instructions. Better result this time: I can at lease see "login with facebook" button.
But my app crashes the moment I clock on it. After running debugger, I realized it's due to facebook not having been set up on my emulator. Any idea how to do that using facebook android sdk 4.16 on mac? All posts I could find so far reference older sdks, specially talking about FBAndroid.apk that I can't find..

Then:
------

Tried to change the behavior to web, same result. For your reference, below is the output in the debugger:

Console was cleared
index.android.bundle:41249Running application "androidS" with appParams: {"initialProps":{},"rootTag":1}. DEV === true, development-level warning are ON, performance optimizations are OFF
index.android.bundle:81456Triggering 'onLoginNotFound' event
index.android.bundle:1507Object {declinedPermissions: Array[0], provider: "facebook", message: "No user found", type: "cancel"}

conversation started in #72

**Comment by lwhiteley** [comment]
@saeed2402 when you touch the button in web behaviour mode, it crashes the app as well?

**Comment by saeed2402** [comment]
Yes

**Comment by lwhiteley** [comment]
So to install the facebook app you would usually ned to flash the emulator.

So i usually use Genymotion and use the following steps:

https://github.com/codepath/android_guides/wiki/Genymotion-2.0-Emulators-with-Google-Play-support

This will give you access the Google Play and you should be able to install it without issues

**Comment by lwhiteley** [comment]
I will test without the facebook app on my emulator and see if I can reproduce as well.

**Comment by saeed2402** [comment]
Thanks @lwhiteley , I'm on it. Will let you know how it went as well.

**Comment by lwhiteley** [comment]
I tested the button without the FB app currently and it opens a webview as fallback

however I see some changes for the latest SDK

https://developers.facebook.com/docs/facebook-login/android#chrome_custom_tabs

seems they added a chrome activity as well in the latest sdk. ill test and see how that works

**Comment by lwhiteley** [comment]
upgraded and still no issues

Let me know the specific emulator you were using and version of android

Thanks

**Comment by saeed2402** [comment]
Do I need to get Google Play running in the simulator to be able to test my app?

**Comment by lwhiteley** [comment]
not reall, you just need google play as an easy way to install the facebook app
there is another way to just get the facebook app directly but that has never worked out for me so I couldnt recommend it

**Comment by saeed2402** [comment]
Can we Skype maybe @lwhiteley ? my id is: saeed_barghi

**Comment by lwhiteley** [comment]
cool added you

**Comment by lwhiteley** [comment]
k closing this due to issue resolved 👍
