### ISSUE TITLE
get Error :: add native plateform in your app setting

### ISSUE THREAD

**Issue by mvnnn** [magus/react-native-facebook-login#174]
```
Plateform: Android
react-native: 0.34.0
```
when i click on facebook button i get Error "add native plateform in your app setting"

**Comment by lwhiteley** [comment]
means you most likely have outstanding things to do in your facebook developer settings

the application you created on developer.facebook.com needs to target  android native platform

**Comment by mvnnn** [comment]
@lwhiteley thanks buddy. it's working :+1:
