### ISSUE TITLE
How to get the email account

### ISSUE THREAD

**Issue by yellowbang** [magus/react-native-facebook-login#176]
After successful login, i get token and userId from the data.credentials. Is there any method that I can get the email and other information? Thank you.

**Comment by lwhiteley** [comment]
For android it is provided with the payload you get on login, however with IOS you would have to use the graph API somehow similar to the Mock button for IOS.

https://github.com/magus/react-native-facebook-login/blob/master/example/components/Login.js#L87

**Comment by tarun29061990** [comment]
I am not getting email with the payload on android

**Comment by lwhiteley** [comment]
did you log out the payload that is returned onLogin and see the data structure?

you should see: 
![https://i.imgur.com/LAuIYhd.png](https://i.imgur.com/LAuIYhd.png)

where the profile object would have the email

**Comment by yellowbang** [comment]
There is no data.profile.email in the object. 

@lwhiteley 
Thanks for your hints in the first reply. I figure out by using the following api we can get the email. After we login to facebook, we can do:

var api = 'https://graph.facebook.com/v2.8/' + data.credentials.userId +
                     '?fields=name,email&access_token=' + data.credentials.token;
                   fetch(api)
                     .then((response) => response.json())
                     .then((responseData) => {
                       console.log(responseData.email)
                       };
                     })
                     .done();

**Comment by lwhiteley** [comment]
@yellowbang the profile object is only available for android as i mentioned in my first reply.

that was for @tarun29061990's benefit.

But happy you figured it out

**Comment by tarun29061990** [comment]
This is what is my payload looks like
<img width="274" alt="screen shot 2016-10-26 at 9 51 27 am" src="https://cloud.githubusercontent.com/assets/1535607/19713221/d75f8270-9b61-11e6-817c-f36f67530459.png">

profile object not coming in android. Finally I am using graph api to fetch all the details.

**Comment by lwhiteley** [comment]
interesting, can you show of snippet of how you defined the FBLogin component @tarun29061990

**Comment by tarun29061990** [comment]
```
  <FBLogin
  buttonView={<FBLoginView actions={actions}/>}
        ref={(fbLogin) => { this.fbLogin = fbLogin }}
        loginBehavior={FBLoginManager.LoginBehaviors.Native}
        permissions={["email","user_friends"]}
        onLogin={
          function(e){
            console.log(e);
          }
        }
        onLoginFound={function(e){
            console.log(e);
          }
        }
        onLoginNotFound={function(e){console.log(e)}}
        onLogout={function(e){console.log(e)}}
        onCancel={function(e){console.log(e)}}
        onPermissionsMissing={function(e){console.log(e)}}
      />
```

**Comment by amorenew** [comment]
I use this
https://github.com/facebook/react-native-fbsdk

 ```
AccessToken
                        .getCurrentAccessToken()
                        .then((user) => {
                            alert("Facebook accessToken:\n" + user.accessToken + "\n\naccessTokenSource: " + user.accessTokenSource + "\n\nuserID: " + user.userID)
                            console.log(user);
                            return user
                        })
                        .then((user) => {
                            const responseInfoCallback = (error, result) => {
                                if (error) {
                                    console.log(error)
                                    alert('Error fetching data: ' + error.toString());
                                } else {
                                    console.log(result)
                                    alert('id: ' + result.id + '\n\nname: ' + result.name + '\n\nfirst_name: ' + result.first_name + '\n\nlast_name: ' + result.last_name + '\n\nemail: ' + result.email);
                                }
                            }

                            const infoRequest = new GraphRequest('/me', {
                                accessToken: user.accessToken,
                                parameters: {
                                    fields: {
                                        string: 'email,name,first_name,last_name'
                                    }
                                }
                            }, responseInfoCallback);

                            // Start the graph request.
                            new GraphRequestManager()
                                .addRequest(infoRequest)
                                .start()
                        })
```
