### ISSUE TITLE
 com.facebook.sdk.login error 308

### ISSUE THREAD

**Issue by Fantasim** [magus/react-native-facebook-login#177]
Hey,

I'm using react-native-facebook-login since 5 months, but i've update xcode to 8.0 and now when i'm trying to signin with facebook on simulator (on iOS 10)

i get this error : 

`The operation could not be completed com.facebook.sdk.login error 308.`

How can i fix it ?

**Comment by ronzilca** [comment]
You saved my day!

**Comment by PurushottamPadhya** [comment]
> i've found my error.
> 
> You need to head over to the “Capabilities” section in Xcode and enable “Keychain Sharing”.

Enabling Keychain Sharing now solved, any other solution?
