### ISSUE TITLE
RCTMFBLoginManager. was called with 0 arguments, but expects 1. 

### ISSUE THREAD

**Issue by Fantasim** [magus/react-native-facebook-login#182]
Hey,

I'm trying to use : 

`FBLoginManager.logout()`

to be able to change facebook account when I sign out or to reapply for permissions.

But when i call this method i get this error : 
http://www.yagoshack.fr/?v=simulators.png

What does it mean?

**Comment by lwhiteley** [comment]
it expects a callback.

you can add a noop function if you like

https://github.com/magus/react-native-facebook-login/blob/master/index.android.js#L96

**Comment by lwhiteley** [comment]
worked out?

**Comment by Fantasim** [comment]
I need to add this function in my appdelegate.m that's right ?

**Comment by lwhiteley** [comment]
```js
FBLoginManager.logout((data) => {console.log(data)})
```

**Comment by Fantasim** [comment]
it works perfectly, thanks :)

**Comment by ali-sheikh7712** [comment]
<img width="1130" alt="Screenshot 2022-07-28 at 11 14 57 PM" src="https://user-images.githubusercontent.com/110194615/181608808-9b725660-37f8-4816-aa5b-abd96529a897.png">

**Comment by ali-sheikh7712** [comment]
can anyone help me out of it.

**Comment by tmarkops** [comment]
> 

I have this same issue. Android works fine but I get the same error as you on ios. Did you find a fix? Thanks
