### ISSUE TITLE
doesn't open facebook app on device.

### ISSUE THREAD

**Issue by Fantasim** [magus/react-native-facebook-login#185]
Hey,

I'm actually trying to open facebook app when connect with facebook login.

this is how i import react-native-facebook-login

```
import { FBLoginManager } from 'react-native-facebook-login'
FBLoginManager.setLoginBehavior(FBLoginManager.LoginBehaviors.Native)
```

and this is my facebook connect function

```
connectFacebookClick(){
    FBLoginManager.loginWithPermissions(["email"], (error, data) => {
	if (!error) {
		this.props.connectWithFacebook(data.credentials.token)
	} else {
		console.log("Error: ", error);
	}
   })
}
```

but i continue to open a modal UIWebView to connect on facebook like that : 

http://www.yagoshack.fr/?v=img0298.png

what's wrong ?

**Comment by Mactub07** [comment]
have the same problem

**Comment by lwhiteley** [comment]
not too sure about the ios implementation but have a read here

http://stackoverflow.com/questions/32566734/native-facebook-app-does-not-open-with-facebook-login-in-ios-9

**Comment by Mactub07** [comment]
https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9/
So, it's default behavior at all (for >=iOS9)

**Comment by Fantasim** [comment]
So, there is no way to open facebook app if it is on the device first?

**Comment by Fantasim** [comment]
ok.. i close issue
