### ISSUE TITLE
buttonView on ios does not work?

### ISSUE THREAD

**Issue by Grundmanis** [magus/react-native-facebook-login#190]
On ios is showing default blue button view , but on android this prop is working correctly. How can i change button view on ios ?

**Comment by Grundmanis** [comment]
anyone?)))

**Comment by lwhiteley** [comment]
buttonView was only implemented for android to date.

see #91.

if you want to customize iOS for now just use the mock button

Or maybe submit a PR if you want to help out

**Comment by lwhiteley** [comment]
this is a duplicate, so will close
