### ISSUE TITLE
Step 3 in Android Setup Unclear 

### ISSUE THREAD

**Issue by TannerPlauche** [magus/react-native-facebook-login#191]
Coming from web development, I am not sure how to handle the instruction for android setup: 

```
import com.magus.fblogin.FacebookLoginPackage; // <--- import

public class MainApplication extends Application implements ReactApplication {

    ...

    @Override
    protected List<ReactPackage> getPackages() {
        return Arrays.<ReactPackage>asList(
            new MainReactPackage(),
            new FacebookLoginPackage() // <------ add the package
        );
    }

    ...
}
```

I am simply not sure where to add this import and class. There is not a file specified for this code. It seems to be a continuation of the instructions for the build.gradle file, but that doesn't seem right. Any suggestions?

**Comment by lwhiteley** [comment]
if you look at your MainApplication file properly you just need to insert the lines for the comments you see.


Or just run 
`react-native link react-native-facebook-login` from the command line

**Comment by TannerPlauche** [comment]
Thank you!

Tanner Plauché
720-222-1037

"У нас не любят свободу недостаточно. " -Alexandr Solzhenitsyn
