### ISSUE TITLE
How do i logout without using native button

### ISSUE THREAD

**Issue by salilbajaj** [magus/react-native-facebook-login#194]
After response from fb login.. I am signing in locally which refreshes hamburger menu. Now i am logging out locally but not being able to find the event which can logout fb also. Observe in last screenshot .. Fb button still shows logout because am not calling any event to log it out. Need to know how can i logout without clicking on it.
![screen shot 2016-12-28 at 6 08 40 pm](https://cloud.githubusercontent.com/assets/14991148/21522116/e69fe628-cd28-11e6-8ddb-9b4f44aa41ae.png)
![screen shot 2016-12-28 at 6 09 08 pm](https://cloud.githubusercontent.com/assets/14991148/21522121/ec0394c0-cd28-11e6-8775-311bfee81adc.png)
![screen shot 2016-12-28 at 6 09 16 pm](https://cloud.githubusercontent.com/assets/14991148/21522122/eec800d8-cd28-11e6-9dd6-95b5a6f035c8.png)

**Comment by lwhiteley** [comment]
check #157

**Comment by salilbajaj** [comment]
Thanks i already tried this.fbLogin.logout() .. Wont work.
Used the other 
FBLoginManager.logout() which gives this error
![screen shot 2016-12-28 at 6 32 15 pm](https://cloud.githubusercontent.com/assets/14991148/21522511/2a8c5a08-cd2c-11e6-92c9-5aa4c1dd4c90.png)

**Comment by lwhiteley** [comment]
That is only for android though. For IOS you would need to use the FBLoginManager

**Comment by lwhiteley** [comment]
also The error you are seeing just suggests you are missing the callback

```
 FBLoginManager.logout((data) => {
   //do something
})
```

**Comment by salilbajaj** [comment]
Ok.. Will try that.. Thanks (y)

**Comment by lwhiteley** [comment]
did it work out?

**Comment by salilbajaj** [comment]
Yea it did.. Thanks alot for the help ..

**Comment by Tony1106** [comment]
That's cool. It works perfectly for me. Thanks a lot!!!
