### ISSUE TITLE
Unable to view user info in successful login response object

### ISSUE THREAD

**Issue by paulokuda** [magus/react-native-facebook-login#195]
After I login and hit the `onLogin` callback, I can't find any user related information in that object. The permissions array says I have access to all of these different fields, but where can I find them?

Here is my `FBLogin` component.
```
<FBLogin
            permissions={['email', 'user_friends', 'public_profile', 'user_posts', 'user_videos']}
            loginBehavior={FBLoginManager.LoginBehaviors.Browser}
            onLogin={(data) => { console.log(data) }}
            onLogout={function(){
              console.log("Logged out.");
            }}
            onLoginFound={function(data){
              this.setState({ currentUser: data.credentials });
            }.bind(this)}
            onLoginNotFound={function(){
              console.log("No user logged in.");
            }}
            onError={function(data){
              console.log("ERROR");
              console.log(data);
            }}
            onCancel={function(){
              console.log("User cancelled.");
            }}
            onPermissionsMissing={function(data){
              console.log("Check permissions!");
              console.log(data);
            }} />
```

Screenshot of the response object.
<img width="522" alt="screen shot 2017-01-01 at 9 53 02 pm" src="https://cloud.githubusercontent.com/assets/6726318/21585044/2bb6ef58-d06d-11e6-83da-48ff3be43966.png">

**Comment by Monte9** [comment]
@paulokuda when the user clicks on login, Facebook only returns a `userId` & `token`. In order to get other user information such as name, email, profile picture etc.. you need to make another API call like such:

```js 
var user = this.props.user
    var api = `https://graph.facebook.com/v2.3/${user.userId}?fields=name,email&access_token=${user.token}`;

    fetch(api)
      .then((response) => response.json())
      .then((responseData) => {
        _this.setState({
          info : {
            name : responseData.name,
            email: responseData.email,
          },
        });
      })
      .done();
```

I would suggest you explore the [Facebook Graph API documentation](https://developers.facebook.com/docs/graph-api) to learn more.

**Comment by paulokuda** [comment]
thanks for the response @Monte9 - much appreciated!

**Comment by AmitPandya007** [comment]
how to set the state values with onLogin object?
