### ISSUE TITLE
AccessToken is null after restart

### ISSUE THREAD

**Issue by Amurmurmur** [magus/react-native-facebook-login#197]
Guys do you experience the same thing? AccessToken.getCurrentAccessToken() returns null after application restart, even tho it returns valid access token upon a successful login.

**Comment by skleest** [comment]
same here--using asyncstorage for now to manually store accesstoken, any better way?

**Comment by Amurmurmur** [comment]
Yeah, easy, just use Facebook SDK 4.17, in 4.18 they have a bug, you can check it in the bug thread.

I switched to FBSDK 4.17.0 and no problem so far.

Hope this helps.
