### ISSUE TITLE
Logout programmatically

### ISSUE THREAD

**Issue by agolovenko** [magus/react-native-facebook-login#20]
Hi, thanks for a great plugin!
I'm using FBLogin button in my app as one of the ways for authorising users. And it works great until the user needs to logout the from the app. The problem is that I can not propagate an app logout event to FBLogin button and even if user has already logged out from my app he still sees "Log out" text on FBLogin button. Thus the user needs to press log out again: this time on FBLogin button.
 
Would rather do it programmatically so the logged out user would see a "Login with Facebook" text.

**Comment by magus** [comment]
https://github.com/magus/react-native-facebook-login/blob/master/example/components/facebook/FBLoginMock.js

Check out the handleLogout method where you see I programmatically log out. Try that out and let me know if it solves your issue! You can also use this mock button I've built, it is visually identical to the actual FB login button.

**Comment by agolovenko** [comment]
Thanks! Worked great, just what I needed.

**Comment by 6thfdwp** [comment]
I tried this way on Android, but it doesn't seem to work.

I manually call `FBLoginManager.logout()` in our own logout process,  then when I enter to log in view again, the button still showing 'Logout from Facebook'.  
I looked into custom FBLogin view in `index.android.js`, which calls the same method on its press handler. Then I exit and enter to log in view it shows the correct 'Log in with Facebook'.

Am I missing something? NOTE, this is for Android. Any suggestion will be appreciated!

**Comment by 6thfdwp** [comment]
Sorry, turned out that the callback that get passed in to `FBLoginManager.logout() ` got some problem, then the actual `logout` method doesn't get invoked properly. So the button state doesn't get changed either. 

It works fine now. Thanks!

**Comment by alxvallejo** [comment]
I called `const FBLoginManager = require('NativeModules').FBLoginManager;`

and 

```
FBLoginManager.logout((error, data) => {...
```

and i get FBLoginManager.logout is not a function

**Comment by lwhiteley** [comment]
https://github.com/magus/react-native-facebook-login/blob/master/index.android.js#L16

**Comment by tastycode** [comment]
@alxvallejo This is working for me

```
import { LoginManager } from 'react-native-fbsdk'
LoginManager.logOut()
```

https://github.com/facebook/react-native-fbsdk/blob/master/js/FBLoginManager.js#L115

**Comment by DavitVosk** [comment]
@tastycode LoginManager.logOut() does not work here on IOS app. Did you use it for Android?

**Comment by tranduykhanh** [comment]
This method is exist but seem does not work 😢 
`
import { FBLoginManager } from 'react-native-facebook-login'
FBLoginManager.logout(() => { console.log('Logout facebook ok!') })
`

**Comment by rsp8055** [comment]
@DavitVosk Yes. 
It's not working in android too.

**Comment by ttruongatl** [comment]
@DavitVosk `LoginManager.logOut()` works fine on iOS as well.

**Comment by SMKH-PRO** [comment]
```
import { LoginManager} from "react-native-fbsdk";
LoginManager.logOut()
```

Works Good on Android!, 
However it is not a promise, and one more thing to understand, this function does not logout user from your application, you have to handle that yourself.

This function will logout user from the Facebook login webview.

**Comment by hayderespit** [comment]
You have to use this function before launch logOut function

```
LoginManager.setLoginBehavior('browser');
```
