### ISSUE TITLE
Login screen uses WebView even though loginBehavior is set to Native

### ISSUE THREAD

**Issue by jshumakerpruitt** [magus/react-native-facebook-login#209]
I tried the `Defaults` and `Exhaustive` sample code, but, in both cases, the login screen is a WebView with an address bar.

<img width="376" alt="screen shot 2017-02-10 at 2 09 07 pm" src="https://cloud.githubusercontent.com/assets/957598/22817733/98c90af2-ef9b-11e6-8763-729a9f0e50d6.png">

**Comment by lwhiteley** [comment]
refer to #185
