### ISSUE TITLE
Setting up the project

### ISSUE THREAD

**Issue by tnguyen42** [magus/react-native-facebook-login#22]
Hi,

I've just been able to make everything work with a little struggling, so here are a few suggestions to make it easier to understand:
1) I think the .framework files can be put at different places, but a screenshot of where you could put them could save a lot of time.
2) About the last code to import into the AppDelegate, it would be nice to write it's in AppDelegate.m and separate the import part from the Facebook SDK part, telling import should be at the beginning and the other part should be before the `@end`.

Excellent plugin though, works perfectly for me until now!

**Comment by magus** [comment]
Hey tnguyen42 can you describe what's not working, share an error screen or something? Is it just the documentation is lacking or is there an actual error when you try to use the project?

**Comment by magus** [comment]
I'm definitely open to updating the documentation to be more specific clear, I spent a lot of time on it but I know it's tricky. I don't have time to learn how to make a pod and last I tried there were issues using the Facebook SDK pod, but I imagine that'd be easier on the whole installation process.

**Comment by tnguyen42** [comment]
Hi,
I actually found a way out, so it was just about the doc. Then later, I discovered... Facebook work deprecated a lot of people's work. Sorry man...
Here's the official facebook login plugin: https://github.com/facebook/react-native-fbsdk

**Comment by magus** [comment]
Thanks for the feedback!
