### ISSUE TITLE
iOS login response does not contain profile data 

### ISSUE THREAD

**Issue by abhisheknalin** [magus/react-native-facebook-login#225]
I implemented facebook login for both android and ios app. I followed all the instructions and it is working perfectly on Android. It works on iOS also but the response does not contain 'profile' data.

Android Response:
```
`{ 
declinedPermissions: [],
provider: 'facebook',
profile:{ 
id: '121212121212121212',
name: 'XYZ',
email: 'xyz@gmail.com',
first_name: 'XYZ',
last_name: 'XYZ',
age_range: { min: 21 },
link: 'https://www.facebook.com/app_scoped_user_id/121212121212121212/',
picture: { data: { is_silhouette: false,url: 'https://scontent.xx.fbcdn.net/v/t1.0-1/12/12.jpg?oh=12&oe=12' } },
gender: 'male',
locale: 'en_US',
timezone: 5.5,
updated_time: '2017-02-01T08:16:35+0000',verified: true },
type: 'success',
credentials: { 
permissions: [ 'public_profile', 'contact_email', 'user_friends', 'email' ],
tokenExpirationDate: '2017-05-13T14:56:36.690+0530',
userId: '1212121212121212121',
token:'ababababababababbababababa' } 
}
```

But on ios the response is incomplete and there is no profile data:

```
{ 
declinedPermissions: [],
credentials: { tokenExpirationDate: '2017-05-14T14:58:09+05:30',
permissions: [ 'email', 'contact_email', 'user_friends', 'public_profile' ],
userId:'12121212121212121',
token:'abababababababababababababa' },
  missingPermissions: [] 
}
```

The code is same for both Android and iOS. And I did all the configuration changes in xCode. Is there something else needs to be done to get the profile data in iOS?

**Comment by ABleas** [comment]
I'm seeing the same thing, no profile data on iOS only. Same result whether I log in with the FB app or mobile web.

**Comment by abhisheknalin** [comment]
I was able to solve this issue. Actually you need to do another API call to get the profile data. You have to send the token which was generated into this API call:
```
 fetch('https://graph.facebook.com/v2.5/mefields=email,name,first_name,last_name,friends&access_token=' + YOUR_GENERATED_TOKEN)
        .then((response) => response.json())
        .then((json) => {
        })
        .catch(() => {
          reject('ERROR')
        })
```

**Comment by ABleas** [comment]
Thanks for posting the solution!

**Comment by abhisheknalin** [comment]
Yes, I somehow missed it. Thanks @ABleas for pointing it out. I have edited my answer.

**Comment by vvkaghera** [comment]
Can anyone help me for the same issue?

https://github.com/magus/react-native-facebook-login/issues/74#issuecomment-353368677

**Comment by siddhuchowdary** [comment]
@abhisheknalin can you brief where & when to call the fetch(); api regarding this issue

**Comment by samsun009** [comment]
> I was able to solve this issue. Actually you need to do another API call to get the profile data. You have to send the token which was generated into this API call:
> 
> ```
>  fetch('https://graph.facebook.com/v2.5/me?fields=email,name,first_name,last_name,friends&access_token=' + YOUR_GENERATED_TOKEN)
>         .then((response) => response.json())
>         .then((json) => {
>         })
>         .catch(() => {
>           reject('ERROR')
>         })
> ```

its only getting name not email and other profile info.
