### ISSUE TITLE
Please update project for xcode 8.3

### ISSUE THREAD

**Issue by und3fined** [magus/react-native-facebook-login#230]
Hi there,

I encountered a bug related to "Duplicate interface definition".
I do not know how to fix it. 
Please help.

![Error](https://4.downloader.disk.yandex.com/preview/d4035a060466ece47afc0146659e787413c5ec3654d51ae40eb1c9cafbd9e6b8/inf/Sv-X_3tZJ0Tw_p8DbO3W5i5brARq1fXT5UAsRDilBDuE7Zw-uubbGTnDbVB01-DlXuEULEmZw1nsRR-ThMTIbg%3D%3D?uid=0&filename=Screen%20Shot%202017-04-03%20at%209.37.15%20AM.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&size=XXL&crop=0)

**Comment by stevenconner** [comment]
I'm having the same problem, is there a way we can download a previous version of xcode or something as a workaround right now?

**Comment by pmadruga** [comment]
I had the same issue but in my case it wasn't related to xcode version, so I was able to solve it using [this](https://github.com/magus/react-native-facebook-login/issues/216) solution. Could that help?

**Comment by und3fined** [comment]
I used react-native-fbsdk instead of this library.
