### ISSUE TITLE
Given URL is not allowed by the Application configuration Issue on android 5.x.x

### ISSUE THREAD

**Issue by kenma9123** [magus/react-native-facebook-login#234]
I'm having an issue about the login process on Android 5.x.x on Android 6.x.x it works just fine. I got an error like 

```
Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.
```

Does anybody able to fix this? Thanks

**Comment by Talor-A** [comment]
Hi how did you fix this??

**Comment by kenma9123** [comment]
@Talor-A if you're app is published(the released version is compiled). Make sure your facebook app is also set to public.
