### ISSUE TITLE
Button not rendered correctly ( no text )

### ISSUE THREAD

**Issue by MocanuMarius** [magus/react-native-facebook-login#237]
Hey , my Login button is very small. it's just a recrangle with no text inside of blue color. :/ Any ideaas why ?

**Comment by MocanuMarius** [comment]
Nevermind..now i see it takes a Buttonview parameters but it's only listed under android setup not in the main documentation.

**Comment by JoseGibran** [comment]
Can you give us and example what did you do?

**Comment by MocanuMarius** [comment]
@JoseGibran you can close the issue, the only thing is to update the docs to include that ButtonView parameter, for now i think it's in the wrong 'place'. :)
