### ISSUE TITLE
react-native-facebook-login getting picture

### ISSUE THREAD

**Issue by edcalderin** [magus/react-native-facebook-login#246]
Hi.

I am using React-native-facebook-login. It works perfectly but now, I wish to get the picture in high resolution:

 FBLoginManager.loginWithPermissions(["email"], function(error, data){
        if (!error) {
            console.log("Login data: ", JSON.parse(data.profile))
        } else {
            console.log("Error: ", error);
        }
        })
data.profile returns all of data but picture profile in low resolution. If I write FBLoginManager.loginWithPermissions(["email", "picture.height(250)"], function(error, data){
It returns an error: Invalid Scope (picture).

How could I solve that?

**Comment by maggialejandro** [comment]
"picture.height(250)" is not a valid permission
Here is a list with all available permissions

https://developers.facebook.com/docs/facebook-login/permissions
