### ISSUE TITLE
"App ID not found" Error even though it is there in Info.plist

### ISSUE THREAD

**Issue by adamwan92** [magus/react-native-facebook-login#254]
Tearing my hair out! How frustrating, it keeps crashing the app and system log says it's asking for the App ID. Have followed the instructions to a tee and I can't see anything at fault with the .plist

**Comment by kaiserama** [comment]
If this is iOS - go into xcode, Project/Info/URL Types + a url type with the format:
fbxxxxxxxxxxxxxxx (x's being your app id).

Build your xcode project
Run `react-native run-ios`

That fixed the issues for me.
