### ISSUE TITLE
FacebookLoginPackage.java:20: error: method does not override or implement a method from a supertype @Override

### ISSUE THREAD

**Issue by martinchristov** [magus/react-native-facebook-login#264]
`node_modules/react-native-facebook-login/android/src/main/java/com/magus/fblogin/FacebookLoginPackage.java:20: error: method does not override or implement a method from a supertype
    @Override
    ^
1 error
:react-native-facebook-login:compileReleaseJavaWithJavac FAILED`

this happened after updating to android build tools 25
Is there any quick fix for it?

**Comment by haseebnaseem** [comment]
Did you solve this ? Hitting the same error.

**Comment by martinchristov** [comment]
I was wrong in my assumption of the cause of the issue. Eventually some of the solutions in the other issues raised worked, but I no longer remember which one :/
