### ISSUE TITLE
undefined is not an object (evaluating '_react.PropTypes.array')

### ISSUE THREAD

**Issue by jnrepo** [magus/react-native-facebook-login#265]
Having issues on react-native 0.47.1. This is because `PropTypes` was migrated into its own support module and moved out of `React`. Will there be an update for 0.47.X versions?

https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

![screen shot 2017-09-01 at 5 36 23 pm](https://user-images.githubusercontent.com/5111058/29991468-579c17cc-8f3c-11e7-9348-8b7511795f00.png)

**Comment by dewhacker** [comment]
Having the same issue:
react-native: 0.46.0
react: 16.0.0-alpha12
react-native-facebook-login: 1.5.0

**Comment by jnrepo** [comment]
@dewhacker this branch worked for me, not merged yet though https://github.com/magus/react-native-facebook-login/pull/251

**Comment by magus** [comment]
Just merged this branch, thanks for reporting the issue!
