### ISSUE TITLE
FBManager.Events undefine

### ISSUE THREAD

**Issue by messiBob** [magus/react-native-facebook-login#266]
I have a question ? when I npm install react-naitve-facebook-login , Should I setting the FBSDK in the xcode again ? i did all of it, add the info.plist,add the framework, when i use it ,first it have a warnning that is MFBLogin native component is does not exist,then i click the my button to facebook login page, it have a red screen error, it is ' FBManager.Events is undefine',please help,my react-native version is 0.47.1

**Comment by magus** [comment]
Should be fixed as of 1.6.0

**Comment by Pau1fitz** [comment]
still seeing the same issue
