### ISSUE TITLE
Add android support

### ISSUE THREAD

**Issue by joevp** [magus/react-native-facebook-login#27]
Is it possible include the [login for Android SDK](https://developers.facebook.com/docs/facebook-login/android)?

**Comment by magus** [comment]
Oof, this is definitely not something I see myself doing anytime in the near future. Going to leave this open though just in case someone wants to do a pull request for it.

**Comment by Roconda** [comment]
+1. Love to see this as well. Hoping for an Android PR.

**Comment by httpNick** [comment]
I am really wanting to do this for Android. I am thinking it will be similar to either of these two examples.. which do you think? 

https://facebook.github.io/react-native/docs/native-components-android.html#content

or

https://facebook.github.io/react-native/docs/native-modules-android.html#content

It's a little dense for me, but id love to implement it.

**Comment by magus** [comment]
I think you'll want to use the second link there, it'll be a native module that wraps the Android SDK facebook login button.

https://developers.facebook.com/docs/facebook-login/android

**Comment by Sh3rawi** [comment]
+1 .
Any updates on this ? @httpNick

**Comment by httpNick** [comment]
Yeah I actually figured it out. @Sh3rawi . Once I figure out how to contribute the working version to this repository you'll see a PR for with it.

**Comment by lalith26** [comment]
@httpNick Hi Nick, Is the support for android coming soon to this repo. I have been searching constantly and have even tried doing it. But I am not able to get the activity result from the LoginActivity in onActivityResult() which Facebook launches. So, I am really hoping to see this working in code.

**Comment by magus** [comment]
Nick all you need to do is click the fork button on this repository, clone the forked repository, add your changes to the forked repository you clone on your local machine, then push the changes back to Github. Then you can create a PR and reference your forked repository. 

https://help.github.com/articles/fork-a-repo/

**Comment by magus** [comment]
If we don't see action by next Saturday I may bump this up and just get it done this Saturday.

**Comment by brysgo** [comment]
:eyes:

**Comment by pagrawl3** [comment]
Would love to see this ! If you could point me in the right direction, I would love to see if I can get the Android version working.

**Comment by lalith26** [comment]
Guys, I have tried this in android. I wrote a custom android module which launches an activity. In that activity, I have just used LoginManager to start the login process. The LoginManager launches the LogicActivity of Facebook. The login flow completes smoothly and I get the result in onActivityResult in my CustomActivity. From here, I dont know how to pass the result back to the custom android module. Since the custom android module is not an activity, I am not able to pass the result back nor am I able to pass the Callback to my Custom Activity because Callback does not implement Serializable or Parcelable. I am just stuck with the last step. Would be great if some one know how to solve that !!

**Comment by Sh3rawi** [comment]
@lalith26  is it possible to launch the LoginManager from the module directly instead of creating a custom activity that launches it ?

**Comment by lalith26** [comment]
@Sh3rawi Hi, I tried launching the LoginManager from the Custom android module itself. But the first parameter expects an Activity or a Fragment. So, I could not do it. I am not sure if there is some other way..

**Comment by Sh3rawi** [comment]
@lalith26 i think you are a better Android dev than me, i know little Android myself.
Anyway, i don't know, is there a way to somehow 'cast' the reactContext you have into an Activity or something like that ?

**Comment by lalith26** [comment]
@Sh3rawi I tried that too. It throws an Exception that reactContext cannot be cast to an Activity. The error is not thrown during compile time when I use reactContext.getApplicationContext()..But when the app runs, I get the red screen..So, that did not work..

**Comment by lalith26** [comment]
Guys,
Check this out..
https://github.com/facebook/react-native/issues/3334

Another approach has been suggested in the above link.

**Comment by lwhiteley** [comment]
@lalith26 i checked it out..seems cool..took out the facebook classes, dropped it into my app and got it to work.

if anyone is implementing this you may want to tweak the GraphRequest to get back the fields you want.

or possibly provide a way to make it configurable

just a heads up :)

eg. 
```java
GraphRequest request =  GraphRequest.newMeRequest(
                                    loginResult.getAccessToken(),
                                    new GraphRequest.GraphJSONObjectCallback() {
                                        @Override
                                        public void onCompleted(JSONObject me, GraphResponse response) {
                                             ...
                                            }
                                        }
                                    });
                            Bundle parameters = new Bundle();
                            String fields = "id,name,email,first_name,last_name," +
                                    "age_range,link,picture,gender,locale,timezone," +
                                    "updated_time,verified";
                            parameters.putString("fields", fields);
                            request.setParameters(parameters);
                            request.executeAsync();
```

**Comment by magus** [comment]
@lwhiteley Are you volunteering to take a first stab at a PR for Android support? :+1:  :laughing:

**Comment by lwhiteley** [comment]
if no one else attempts it by weekend.. i guess i could take a stab at it
never did an integration in a project for both IOS and android before so may ask for some guidance @magus

**Comment by jforaker** [comment]
@lwhiteley I would be forever grateful to see how you implemented it :)

**Comment by satya164** [comment]
@lwhiteley I could help on the Android part if you want.

**Comment by lwhiteley** [comment]
that would be helpful man, ill let you know when im ready @satya164

**Comment by satya164** [comment]
@lwhiteley Awesome :)

**Comment by jforaker** [comment]
Just wanted to post here a gist I created showing how I implemented @satya164's FacebookLoginModule successfully with my Android app:

https://gist.github.com/jforaker/bbd1b27138f259f2d7fa  

Its not ready yet to be a npm module yet, but it should be straight forward to get up and running if you follow the steps

**Comment by magus** [comment]
Wow awesome, feel free to pull request this into the repo here! That would be great so that anyone can download the NPM package and work in either Android or iOS!

**Comment by lwhiteley** [comment]
@magus  I was wondering about how similar the Interface should be to the iOS version.

Should it be the same or is it ok to have an 'AndroidFBLoginManager' (just to throw out ideas)

**Comment by magus** [comment]
Well, if the user-facing interface is the same then the existing usage examples can be reused which will save us from writing more documentation. That having been said, if there is a compelling reason to change things I am not going to push back much since we can iron things out later, if necessary.

**Comment by lwhiteley** [comment]
kk cool, i started working on it, code pretty much similar to that of what @jforaker did

Ill see how similar i can get the react component to be with interface and functionality

**Comment by lwhiteley** [comment]
WIP: https://github.com/lwhiteley/react-native-facebook-login
Setup Docs: https://github.com/lwhiteley/react-native-facebook-login/blob/master/Android.md

Notes:
- no logout functionality yet on button  yet (FBLoginManager has a logout api though)
- FBLogin is a custom button and not a wrapped version of the Android FBLoginButton (may implement this)
- Button 

This needs some testing right now.. anyone can volunteer

`npm install --save https://github.com/lwhiteley/react-native-facebook-login`

Anyone that wants to contribute to this feature on my branch/repo I can add you as a colloborator :+1:

**Comment by Sh3rawi** [comment]
@lwhiteley i've installed the package. When using the simulator, or a phone that doesn't have the mobile app installed; it works just fine and returns all the data. However, when the Facebook app is installed, i get an error of the keyhash not being registered on my app settings in FB. I added the keyhash to the app settings, but still i get the same error. 
I don't know if this problem is because of my config or something in the package( how come it signs-in when there is no FB app installed but returns an error if its installed?).

**Comment by Sh3rawi** [comment]
@lwhiteley i've installed the package. All is well with FBLoginManager while trying it.

**Comment by lwhiteley** [comment]
works with native app or web sign in for you? @Sh3rawi

**Comment by Sh3rawi** [comment]
@lwhiteley if the fb app is installed it opens it, if its not, the fb activity inside my app will open itself (it doesn't open the web browser).

**Comment by lwhiteley** [comment]
oh no shouldn't be a full browser, just a webview with fb login if the app isnt installed but yea seems to be fine then

**Comment by Sh3rawi** [comment]
yup thats what i meant. Good work man thanks (Y)

**Comment by magus** [comment]
@lwhiteley  Going to submit a PR?

**Comment by niftylettuce** [comment]
@magus wow, awesome! @lwhiteley let's get this in!

**Comment by akiran** [comment]
+1 Tested facebook login in my app. It worked.
Look forward for merging this

**Comment by lwhiteley** [comment]
sorry for the delay folks. State now added to button. can login/logout now .. test away

please continue conversation in PR #33

**Comment by niftylettuce** [comment]
@lwhiteley @akiran @magus @Sh3rawi Hey guys, I noticed that the data object returned in the callback is different on Android than it is on iOS.

Specifically, to access the token, it is available on `data.token` in the callback on Android and on iOS it is on `data.credentials.token`.  Is there a way we can normalize this?  Am I doing something wrong?

**Comment by valetarton** [comment]
^^ @niftylettuce , this also has occurred for me
Android: 
```
{
eventName: "string",
expiration: "string",
profile: "JSON.strinfiied string",
provider: "string",
token: "string",
type: "string" 
}
```
IOS:
```
{
credentials: {object},
missingPermissions: [array]
}
```
Guess I'll have to target by OS for now.

**Comment by lwhiteley** [comment]
@niftylettuce thanks for pointing this out. There is a similar issue about unifying the APIs ( #55 )

@niftylettuce or @valetarton  feel free to create an issue if issue #55 is not specific enough for your query

@magus can this issue be closed now since we actually have android support? 
all other issues can be created as separate items so they aren't lost

**Comment by toomeymarc** [comment]
Hi there !
Unfortunately I'm unsure to where I'm suppose to add the javascript in step 6 of your tutorial to set it up for Android.
Could someone give me a hand ?

https://github.com/magus/react-native-facebook-login/blob/master/android/README.md

**Comment by jforaker** [comment]
@toomeymarc if you use the Github to search the repo for `FBLogin` you will see it is used here https://github.com/magus/react-native-facebook-login/blob/master/example/components/Login.js
in `/components/Login.js`, which is the called by the `initialRoute` prop of the main NavigatorIOS component in src/index.ios.js  (you will use the same pattern for android)

```
var AppEntry = React.createClass({
  render: function() {
    return (
      <NavigatorIOS
        style={styles.container}
        itemWrapperStyle={styles.allPages}
        initialRoute={{
          title: 'Login',
          component: Login,   /// <---------------- there
        }}
      />
    );
  }
});
```
