### ISSUE TITLE
View.propTypes has been removed in 0.49

### ISSUE THREAD

**Issue by dseipp** [magus/react-native-facebook-login#279]
Unable to run in release mode as my app crashes with `undefined is not an object (evaluating 'l.View.propTypes.style')`.  

react: 16.0.0
react-native: 0.49.4
prop-types: 15.6.0
react-native-facebook-login: 1.6.0

**Comment by GH974** [comment]
Hi, try this solution temporaly,

> in project_name/node_modules/react-native-facebook-login/index.ios.js

add in top import react-native this ViewPropTypes

an exemple after edited
`import {
  View,
  ViewPropTypes,
  StyleSheet,
  NativeModules,
  NativeMethodsMixin,
  DeviceEventEmitter,
  requireNativeComponent
} from 'react-native';`

and bottom file replace in FBLogin.propTypes ={ style : View.propTypes.style} per ViewPropTypes.style 

An exemple after replace

`FBLogin.propTypes = {
  style: ViewPropTypes.style,
  permissions: PropTypes.array, // default: ["public_profile", "email"]
  loginBehavior: PropTypes.number, // default: Native
  onLogin: PropTypes.func,
  onLogout: PropTypes.func,
  onLoginFound: PropTypes.func,
  onLoginNotFound: PropTypes.func,
  onError: PropTypes.func,
  onCancel: PropTypes.func,
  onPermissionsMissing: PropTypes.func,
};`

It's work for me...

**Comment by rmn528** [comment]
when this change is gonna be part from the repo?

**Comment by dseipp** [comment]
@GH974 , appreciate the suggestion.  Unfortunately changing the node module directly only works locally.  The CI build won't pick it up.

**Comment by pekq** [comment]
There's an open PR #273 that fixes this issue.  

So while we wait it to get merged, just change in your `package.json` the key value pair like so:  
`"react-native-facebook-login": "https://github.com/adamonkey/react-native-facebook-login/tarball/patch-1"`

**Comment by holden-caulfield** [comment]
Why is the PR referenced above not merged already? 

This just exploded on my face yesterday when I tried to release a new app for the first time... is particularly nasty because it works just fine on development. And also very hard to hunt down the root cause, just wasted a day of work.

A very simple, straightforward fix for such a blocking issue should got its way into master quite faster

**Comment by aramkarapetian** [comment]
hi guys, we also end up debugging for four hours. How can we help to speed up the merge? Otherwise we will end up forking and other nasty workarounds. Please merge.

**Comment by JanErikFoss** [comment]
Please merge

**Comment by meodemsao** [comment]
please merge

**Comment by magus** [comment]
Thanks for reporting this, the fix is out in version 1.6.1!
