### ISSUE TITLE
Supporting this for React Native 0.12?

### ISSUE THREAD

**Issue by kevinzzz007** [magus/react-native-facebook-login#29]
Hi there, thank you so much for making this and being super responsive with the issues, are you supporting this for React Native 0.12?  I know that the Facebook React Native SDK is broken by the RN 0.12...https://github.com/facebook/react-native-fbsdk/issues/50

**Comment by magus** [comment]
I see no breaking issues in the release notes so I assume 0.12 should work the same as 0.11. Are you seeing a specific issue or just curious?

**Comment by magus** [comment]
Everything works with react-native 0.12. Verified example project with the latest bits from npm

**Comment by kevinzzz007** [comment]
@magus thanks for being so responsive!
