### ISSUE TITLE
Remove FacebookSDK and include via PodFile

### ISSUE THREAD

**Issue by tarrencev** [magus/react-native-facebook-login#3]
What are your thoughts on using CocoaPods to install the FB SDK dependency?

**Comment by magus** [comment]
Looks great, I'm new to iPhone development actually and have seen the term CocoaPods before but this is the first time I'm reading the site. This would significantly reduce the setup overhead and mean the user only has to create an app on Facebook and add the IDs to their .plist, right?

Did you have a pull request or should I add it to my TODO list?

**Comment by tarrencev** [comment]
I'll put together a PR. Would mean the user has to have the CocoaPods cli installed but will be easier in that case.

Also means users aren't cloning an unnecessary copy of the sdk if they are already using it

**Comment by jcgertig** [comment]
any update on this?

**Comment by tarrencev** [comment]
Sorry, I haven't had a chance to look into it yet. Will try find some time soon. But feel free to take a stab if you'd like

**Comment by amccloud** [comment]
Could do something like:

- npm install react-native-facebook-login
- add node_mofules/react-native-facebook-login to Podfile
- pod install

**Comment by tarrencev** [comment]
Don't think I'm going to get around to this, sorry. Closing for now.
