### ISSUE TITLE
App crashes if trying to login via Facebook - no Facebook app installed on emulator

### ISSUE THREAD

**Issue by akhlopyk** [magus/react-native-facebook-login#336]
Hi there!
I got an issue with login via Facebook when Facebook app is no installed on device. My app crash.
Once I install facebook app from google play it works fine. Then remove Facebook app from device my app crash again. This thing is only on Android, since IOs using web to login.

What have I missed?

**Comment by akhlopyk** [comment]
To fix it I have added checker if FB app is installed like this.
`Linking.canOpenURL("fb://") .then((canOpen) => { _code to check if yes here and depends on response Native || WebView || Web }`

**Comment by AmitPandya007** [comment]
> To fix it I have added checker if FB app is installed like this.
> `Linking.canOpenURL("fb://") .then((canOpen) => { _code to check if yes here and depends on response Native || WebView || Web }`

@akhlopyk 
Did it worked on Android and iOS both???

**Comment by akhlopyk** [comment]
@AmitPandya007 
Yes, It works on both systems
