### ISSUE TITLE
GET flow HTTP 1.1 404 when using LoginManager

### ISSUE THREAD

**Issue by matthewswallace** [magus/react-native-facebook-login#34]
I wanted to point out that I was using your example from the Readme file for FBLoginManager.loginWithPermissions and getting an error in the console. Basically 404 because ios 9 simulator was not allowing me to call a URL that hasn't been white listed. 

My xcode project is setup to build for ios 7 however the simulator is running ios 9. It may be worth pointing out that even if you are building for ios 7 if you run your app in ios 9 you will still need to setup the domain white list stuff in your info.plist. https://developers.facebook.com/docs/ios/ios9

**Comment by magus** [comment]
Yep, I think the idea in Apple land is you should always be targeting the latest release. Documentation of Facebook supports this by showing the iOS 9 guide by default.

I'll add a note to the README which is a bit more explicit about this, thanks :+1:
