### ISSUE TITLE
GraphAPI using this framework

### ISSUE THREAD

**Issue by skleest** [magus/react-native-facebook-login#36]
Hi,

Is it possible to use graphAPI using this framework? I have the accesstoken but no data yet (of course).
I tried installing react-native-fbsdk but not working too well, one possibility being that I already have this framework installed via cocoapods. Thank you.

**Comment by magus** [comment]
Sure! You can store and use the token returned with the login credentials to make graph requests on behalf of the user. Of course you'll need to update the permissions you request to include whatever request you're trying to make.

As an example, [take a look at the Login components in the example](https://github.com/magus/react-native-facebook-login/blob/master/example/components/Login.js#L88) I provide with this project. You can see that I use the credentials returned from the login request to then make a subsequent request for the user profile photo.

https://developers.facebook.com/docs/graph-api

**Comment by skleest** [comment]
Thank you!
