### ISSUE TITLE
Android errors

### ISSUE THREAD

**Issue by treeder** [magus/react-native-facebook-login#40]
I've tried all the instructions here: https://github.com/magus/react-native-facebook-login/blob/master/Android.md

And it shows the button. But after I try to login, the app crashes. 

Believe this is the error from LogCat:

```
11-30 10:42:51.078  1337  1356 W WindowAnimator: Failed to dispatch window animation state change.
11-30 10:42:51.078  1337  1356 W WindowAnimator: android.os.DeadObjectException
11-30 10:42:51.078  1337  1356 W WindowAnimator: 	at android.os.BinderProxy.transactNative(Native Method)
11-30 10:42:51.078  1337  1356 W WindowAnimator: 	at android.os.BinderProxy.transact(Binder.java:503)
11-30 10:42:51.078  1337  1356 W WindowAnimator: 	at android.view.IWindow$Stub$Proxy.onAnimationStopped(IWindow.java:534)
```

**Comment by lwhiteley** [comment]
not seeing enough information here to begin to analyze your issue.
What Android OS version is this as well?
is that the only stack trace relating to the issue?

This is the only thing i could find with little context:
http://stackoverflow.com/questions/1573557/how-to-fix-android-os-deadobjectexception-android-x

**Comment by hzyIO** [comment]
+1 I'm getting the same issue. 

I'm using ReactNative 16, Android version 5.1.0 API 22, will check out the link above.

**Comment by lwhiteley** [comment]
Thanks

thats a lot more context, 
this was tested with react-native 14, 

ill have to check it out and see when i get some time.

if its possible, could you try it out with RN 14 and see if you get the same issue

**Comment by hzyIO** [comment]
Seems that I can't get the project to run with RN 14.2, since I'm assuming the project was built with RN 16. I'm getting some other error in RCTNetworking.sendRequest, but I believe thats unrelated to this module.

**Comment by hzyIO** [comment]
Ok I have it working with ReactNative 16.0, Android version 5.1.0. I made a mistake in the setup, by putting my AppId in the AndroidManifest.xml here:

        <meta-data
                android:name="com.facebook.sdk.<I put my appId here>"
                android:value="@string/fb_app_id"/>
            </application>

Real silly in hindsight, but may need to make it expicit that you don't need to change this string at all.

**Comment by lwhiteley** [comment]
@treeder did you double check to see if you followed the setup properly.

@hzyIO glad to know your issue is resolved

**Comment by derese** [comment]
Closing the Issues Helps a lot
