### ISSUE TITLE
Facebook Login “Exception throw” Error via React Native on iOS

### ISSUE THREAD

**Issue by robtg4** [magus/react-native-facebook-login#41]
I have attempted 5x to get Facebook login on my react native app, but it seems the following method has been deprecated:

-http://brentvatne.ca/facebook-login-with-react-native/

Given that "logInWithReadPermissions:" is no longer used by Facebook. When I use the following method (shoen below), which seems to be the newest, I suddenly get a "Exception thrown" error:

https://github.com/magus/react-native-facebook-login
The error looks like the following: (issue stated fully on StackOverflow)

http://stackoverflow.com/questions/34117806/facebook-login-exception-throw-error-via-react-native-on-ios

**Comment by magus** [comment]
Can you share the actual repository by pushing to GitHub? I don't see anything obvious in the snippets but it seems like your Info.plist file is not recognized or parsed correctly for some reason. 

You did set up the app on the developer Facebook site, right? Take a look at the example in this repository and compare it to your own, maybe you'll notice a difference.

**Comment by robtg4** [comment]
Yeah, I followed the SDK build via Facebook exactly. The repo that I'm building is private unfortunately but I will try again now and get back to you tonight

**Comment by robtg4** [comment]
Yeah it still doesn't work - I notice that there are some differences in your AppDelegate.m setup and that of facebook's - mainly the part here:

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];
  return YES;
}

Where they still return YES but you return something different. When I set it up there way and add the edits that you propose, my simulator can't connect to the sever anymore. I'll add you to my repo if you'd like and you can commit - the signup and login components are the frames that have the facebook login

**Comment by magus** [comment]
https://github.com/robtg4/blaclist/blob/master/ios/blaclist/Info.plist

Your plist doesn't have the necessary updates to include the FacebookAppId, for example. I'd recommend going through all the instructions again. Going to close this issue for now since it seems to be related to your configuration.

https://developers.facebook.com/docs/ios/getting-started/#settings

**Comment by robtg4** [comment]
No this is an older version, the version I reverted back to. The one I did
had everything it needed to work per your instructions.

**Comment by robtg4** [comment]
I had to revert it back to what it was before because I couldn't render anything
