### ISSUE TITLE
Could not connect to Development Server after Module Config

### ISSUE THREAD

**Issue by robtg4** [magus/react-native-facebook-login#42]
If you visit my update repo this is the result - this is why when you visited it earlier i had reverted it to an earlier version. 

![screen shot 2015-12-07 at 12 35 24 am](https://cloud.githubusercontent.com/assets/13613075/11619852/829c4ac0-9c7a-11e5-93c1-d37c707c8b7d.png)

**Comment by robtg4** [comment]
Found out it was due to the organization (not the contents) of info.plist - via the way that you have your file organized

**Comment by muchychka** [comment]
Have same issues, guys what you have done for solving that?

**Comment by magus** [comment]
You should double check your plist file. If in doubt, generate a fresh one and add the strings required again. Posting your specific file would help too.
