### ISSUE TITLE
Unable to successfully build without using CocoaPods and !use_frameworks option

### ISSUE THREAD

**Issue by chris-erickson** [magus/react-native-facebook-login#43]
If I follow your directions, I am unable to successfully build the project, giving me the error `'FBSDKCoreKit/FBSDKCoreKit.h' file not found` which is emitted from your project.  I started fresh and followed all the steps, with no luck.  I also had no luck using CocoaPods to include the files like so:

```ruby
platform :ios, '8.0'

target 'MyApp' do
  pod 'FBSDKLoginKit', '4.7.1'
end

target 'MyAppTests' do
  pod 'FBSDKLoginKit', '4.7.1'
end
```
However, if I use the `use_frameworks!` flag, it does work:

```ruby
platform :ios, '8.0'
use_frameworks!  # <--- ADDED

target 'MyApp' do
  pod 'FBSDKLoginKit', '4.7.1'
end

target 'MyAppTests' do
  pod 'FBSDKLoginKit', '4.7.1'
end
```

Any idea what's going on?  I'm inclined to think that I have something messed up in my project, but have no idea where to look.

**Comment by magus** [comment]
Did you follow the steps to add the Facebook SDK to your xcode project?

https://github.com/magus/react-native-facebook-login#adding-the-facebook-sdk

This is just a few lines after the Setup instructions but I feel like the documentation could probably be improved. If this doesn't resolve your issue let's figure out why.

**Comment by chris-erickson** [comment]
Yep, followed those steps.  That's why I'm thinking there is something with my configuration, but I don't really know.

**Comment by magus** [comment]
Mind sharing your repository?

**Comment by chris-erickson** [comment]
Unfortunately I can't on this one.  I know this is not likely easy to diagnose otherwise.

**Comment by maluramichael** [comment]
This doesn't work for me either.
