### ISSUE TITLE
Error: Cannot find module "react-native-facebook-login"

### ISSUE THREAD

**Issue by niftylettuce** [magus/react-native-facebook-login#45]
It's trying to load `index.js` but it doesn't, because there is no index.js file.

Looks like `<FBLogin />` is broken?  Or your documentation is not up to date?

![screen shot 2015-12-07 at 10 59 35 pm](https://cloud.githubusercontent.com/assets/523141/11647454/4fcb0d86-9d36-11e5-90a4-e8d98443ed96.png)

**Comment by magus** [comment]
Would you mind sharing your repository? The names did change but the example project works fine and I just set up a test project, pulled from npm and it all worked. Please make sure you following the instructions under Setup.

https://github.com/magus/react-native-facebook-login#setup
