### ISSUE TITLE
What is the difference between this and what Facebook supports?

### ISSUE THREAD

**Issue by klatchbaldar** [magus/react-native-facebook-login#47]
https://github.com/facebook/react-native-fbsdk

**Comment by eranbes** [comment]
Android version?

**Comment by magus** [comment]
Android support is probably the biggest one.

This library was also created long before Facebook released a similar repository. I mostly wrote it as a learning experience with react-native. That having been said, the react-native-fbsdk repo does have more wrappers for various components of the Facebook API, but I believe you can achieve similar results with either library from the javascript side of things.
