### ISSUE TITLE
[Android] onLogin doesn't trigger

### ISSUE THREAD

**Issue by minibikini** [magus/react-native-facebook-login#50]
After the login screen when it takes me back from facebook to my app, it doesn't trigger onLogin/onLogout/onCancel/onError/onPermissionsMissing and the button text still "Login with Facebook". If I click the login button again it triggers "onCancel" (`{provider: "facebook", type: "cancel", message: "Cannot register multiple callbacks"}`) and opens the facebook login screen.

react-native: 0.16.0
react-native-facebook-login: 1.0.2
Android 5.1.0 (genymotion)

**Comment by babalustu** [comment]
I was having the exact same issue and it was to do with my onActivityResult method in MainActivity.java being entirely commented out. Once I uncommented the login started working

**Comment by minibikini** [comment]
@babalustu thanks a lot for the hint! Turns out I forgot to copy paste the onActivityResult snippet.
