### ISSUE TITLE
iOS doesn't launch Facebook app

### ISSUE THREAD

**Issue by kinhunt** [magus/react-native-facebook-login#54]
Hi:

I have the fb app installed. When the fb login button pressed, the fb app doesn't launch. Instated, the mobile safari is popped. LSApplicationQueriesSchemes has been set. What did I miss? Thank you.

**Comment by Sh3rawi** [comment]
On iOS 9, the default behaviour of the fbsdk is to launch the web safari not the app. On iOS 8 and below the app is invoked as a default.
https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9

**Comment by kinhunt** [comment]
@Sh3rawi Thank you

**Comment by DavitVosk** [comment]
Is there any option to open Facebook app for iOS 9 and after?

**Comment by DavitVosk** [comment]
Even don't get any success when changing behavior to `native`
