### ISSUE TITLE
[IOS] Doesn't display the information when I log in first time

### ISSUE THREAD

**Issue by Davidmeteor** [magus/react-native-facebook-login#57]
Hi,

I followed the example and composed one basic IOS app. But I have one problem here.
The user information doesn't display when I log in first time. (Or, I removed my previous record from Parse backend database)
But, after pressing CMD+R to refresh the APP, it shows up and the information is correct.
Is there anyone knows how to deal with this issue? Thanks a lot!!
![2016-01-07 6 59 08](https://cloud.githubusercontent.com/assets/9524627/12189246/dfb10278-b570-11e5-8391-df77258e7e03.png)

**Comment by magus** [comment]
You might need to do something in the onLogin callback to ensure the requests for whatever user information are done after the login has been completed. Take a look at the example components under the example directory and let me know if that helps. If it doesn't feel free to reopen the issue with a specific code snippet.
