### ISSUE TITLE
Update android instructions for react-native v0.18.0

### ISSUE THREAD

**Issue by faeronsayn** [magus/react-native-facebook-login#58]
Since react-native v0.18.0-rc is out and now the `MainActivity.java` file looks much different, so it'd be great if step 3 in the android instructions can be updated: https://github.com/magus/react-native-facebook-login/blob/master/android/README.md

@lwhiteley

```
...
public class MainActivity extends ReactActivity {
  /**
   * Returns the name of the main component registered from JavaScript.
   * This is used to schedule rendering of the component.
   */
  @Override
  protected String getMainComponentName() {
      return "appname";
  }

  /**
   * Returns whether dev mode should be enabled.
   * This enables e.g. the dev menu.
   */
  @Override
  protected boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
  }

 /**
 * A list of packages used by the app. If the app uses additional views
 * or modules besides the default ones, add more packages here.
 */
  @Override
  protected List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
      new MainReactPackage());
  }
}
```

**Comment by Epotignano** [comment]
This is the only step that changes?

**Comment by faeronsayn** [comment]
@Epotignano, I believe so, have you got it working with v0.18.0-rc?

**Comment by Epotignano** [comment]
I've done the steps for android install, and when the app inits, it shutdowns suddenly so I've removed the plugin, there are any further updates about this issue?

**Comment by HenryStevens** [comment]
I've created a pull request, here: https://github.com/magus/react-native-facebook-login/pull/60, with the updated MainActivity. Works on v0.18.0-rc.

**Comment by mpm** [comment]
I can confirm that #60 works like a charm for my app with v0.18.0. Thanks!

**Comment by brainsqueezer** [comment]
Should have checked issues before. Found same solution.

**Comment by magus** [comment]
All right, it looks like this solution has worked for multiple people so I'm going to merge it. Thanks @HenryStevens. @lwhiteley: Let me know if you have any concerns, also it looks like it may be the same  change as #59 @satya164
