### ISSUE TITLE
Any plans to support a newer version of React Native?

### ISSUE THREAD

**Issue by maggerbo** [magus/react-native-facebook-login#61]
I can't upgrade further than 0.14.2. Am I doing something wrong or are there any plans to support newer versions of react native?

Thanks for a great plugin!

**Comment by Sh3rawi** [comment]
Im on RN 0.18-rc and all is good. What is the problem you face?

**Comment by joewood** [comment]
The binding rule for react-native is >=0.14.2, so failing with 0.18-rc.

**Comment by maggerbo** [comment]
Exactly. I can't get to update React Native to a newer version than 0.14.2
