### ISSUE TITLE
react-native-facebook-login

### ISSUE THREAD

**Issue by BigPun86** [magus/react-native-facebook-login#64]
I am getting "undefined is not a function (evaluating 'FBLoginManager.getCredentials')" on React Native Android Development:

    componentWillMount() {
		var _this = this;
		FBLoginManager.getCredentials(function (error, data) {
			console.log(error, data);
			if (!error) {
				store.dispatch(facebookUserIsLoggedIn(data.credentials));
				Actions.dashboard();
				_this.setState({credentials: data.credentials});
			} else {
				_this.setState({credentials: null});
			}
		});
	}

![screenshot_2016-01-19-10-31-35](https://cloud.githubusercontent.com/assets/7880624/12414850/77e5d886-be98-11e5-80f2-926489e180c2.png)

In my iOS Version this module works great, just having issues on Android

**Comment by lwhiteley** [comment]
currently there is a difference between the android and IOS versions
please see issue #55 

for now you can follow the api/use the login button that comes with the android version
https://github.com/magus/react-native-facebook-login/blob/master/index.android.js

**Comment by BigPun86** [comment]
Okay thanks! But unfortunately it still wont work. It tell´s me now: "undefined is not an object (evaluationg 'FBLoginManager.getCurrentToken')

**Comment by lwhiteley** [comment]
did you set up your main activity correct and add the module there.

please ensure you followed the steps in the setup doc properly. 
https://github.com/magus/react-native-facebook-login/blob/master/android/README.md

**Comment by BigPun86** [comment]
Oh man! Thanks, i switched the branch on git where my setup for Android wasn´t there anymore....
