### ISSUE TITLE
How to console log results from additional fb permissions (eg user_birthday)?

### ISSUE THREAD

**Issue by mhinc14** [magus/react-native-facebook-login#67]
Sorry if this is a noob question but once i log in how do i see the results for additional fb data (e.g user_birthday) in the console. 

I can successfully log in and see profile information in the console. I have also created a test user account via fb to ensure i have access to the permissions such as user_birthday. Now, when i am logging into the app it tells me that the app wants permission to see my birthday and I click okay. However i cant work out how to see this data.

**Comment by magus** [comment]
Take a look at the following component in the examples, it retrieves the user profile photo. 

https://github.com/magus/react-native-facebook-login/blob/master/example/components/Login.js#L86

You can make Facebook Graph API calls for that information assuming you have permissions for it.
