### ISSUE TITLE
Invalid directory on iOS and React 0.18

### ISSUE THREAD

**Issue by brainsqueezer** [magus/react-native-facebook-login#68]
Not sure if it is related to React version but this is what I'm getting in the red screen

    Unable to resolve module react-native-framework-login from
    /Users/myuser/workspace3/myproject/components/Login.js: Invalid directory
    /Users/nodule_modules/reactnative-facebook-login
    
    RCTFatal + 139
    
    [RCTBatchedBridge stopLoadingWithError:] 819
    
    __25-[RCTBatchedBridge start]_block_invoke_2 + 82
    
    _dispatch_call_block_and_release + 5
    
    _dispatch_client_callout + 14
    ...

Seems to be related with the line `var FBLogin = require('react-native-facebook-login');` at components/Login.js line 10 in sample project.

Found a similar error at https://github.com/race604/react-native-viewpager/issues/5 but what they call  destructuring assignment, instead of direct import, didn't worked for me.

I'm pretty new to React and iOS but I tried both by updating the sample project and following instructions from an empty project and I'm getting the same error. I have dedicated hours to this and I'm stuck.

**Comment by camwhite** [comment]
I'm seeing this too when tyring to both es2015 imports and the ole' require. Switching `index.ios.js` to `index.js` solved it for me, but could become problematic when I want to support android.

**Comment by magus** [comment]
Can you link me the repo? `Invalid directory
/Users/nodule_modules/reactnative-facebook-login` seems like it's looking down the wrong path, assuming it should be `/Users/myuser/workspace3/myproject/nodule_modules/react-native-facebook-login`

**Comment by brainsqueezer** [comment]
I have published one of my tests at https://github.com/brainsqueezer/react-test
Yes, my little understanding of how iOs projects are built keeps me from fixing this problem

**Comment by magus** [comment]
Solved by #58?
