### ISSUE TITLE
Cannot manipulate styles?

### ISSUE THREAD

**Issue by mbrochh** [magus/react-native-facebook-login#73]
I'm trying to do this:

```
<FBLogin
    style={{marginTop: 10, borderWidth: 1, flex: 1, height: 100, width: 300}}
    onLogin={function(e){console.log(e)}}
    onLogout={function(e){console.log(e)}}
    onCancel={function(e){console.log(e)}}
    onPermissionsMissing={function(e){console.log(e)}}
/>
```

On iOS, marginTop and bordherWidth works, but the button is quite tiny and I can't get it bigger. On Android, no styles at all are applied. Am I doing it wrong?

**Comment by mbrochh** [comment]
Hmm... looking at the `index.android.js` it very much seems like style override has not been implemented, yet. I guess I'll just build my own FBLogin component then based on that code, facilitating the FBLoginManager component.

**Comment by magus** [comment]
Feel free to shoot a pull request if you extend things, especially android side. I could use help there for sure.

You should be able to wrap the FBLogin button in a view to position it how you'd like, similar to the examples. If you want to style your own button though you can use the LoginMock component as a reference.

https://github.com/magus/react-native-facebook-login/tree/master/example/components

**Comment by qasimalbaqali** [comment]
@magus Editing the styles in LoginMock or FBLoginMock (styles.FBLoginButton) doesn't do the trick. Tried many times playing around with the styles and it doesn't change them.

**Comment by thibthibaut** [comment]
You can cheat a little by using a View which wraps the <FBLogin /> component with the same background color. Then you can adjust the size. Of course the font size won't change but it can be useful.
```
<View style={{ backgroundColor: '425bb4',width:200, height:40 }} >
    <FBLogin style={{ margin: 5 }} />
</View>
```


![sans titre 3](https://cloud.githubusercontent.com/assets/4490506/12953053/254e6e84-d019-11e5-874b-7cceece188c9.png)

**Comment by qasimalbaqali** [comment]
@thibthibaut nice hack, but would suck if you'd use something like TouchableOpacity

**Comment by skizzo** [comment]
So there is no way of actually using a different (read: custom styled) button for login/logout?

**Comment by thibthibaut** [comment]
Actually there is, you just have to use the FBLoginMock instead of the native component. That's what I did at the end, following the example. You can customize your FBLoginMock Component as you please and the behavior is exactly the same as the native Facebook button.

**Comment by braco** [comment]
It would be good if this component just accepted subviews and allowed for an override that way:

<FBLogin><ButtonElement /></FBLogin>

**Comment by qasimalbaqali** [comment]
@braco or better yet directly adding styles to FBLogin component would override the default style that comes with it. Makes it way easier..

**Comment by fforres** [comment]
So, still no subviews?

**Comment by lwhiteley** [comment]
knocking out a lot of issues, may look into this next, while i still got some free time

**Comment by lwhiteley** [comment]
can someone here volunteer to test the mentioned PR
and see if this issue is properly resolved for Android

Please continue the conversation in the Pull Request 

https://github.com/magus/react-native-facebook-login/pull/105

[install from my fork directly to test (using github url)]

please see the updated docs on to reference changes for your issue. 
If not there please suggest it in the PR

**Comment by lwhiteley** [comment]
this should have been resolved by #105

**Comment by trung1008** [comment]
i have same issue, i also no have idea to resolve it. anyone can help me :(

**Comment by rajesh8005** [comment]
Same here please provide any idea to solve this issues....
thanks...
