### ISSUE TITLE
iOS: login() not returning the profile?

### ISSUE THREAD

**Issue by mbrochh** [magus/react-native-facebook-login#74]
I'm trying this:

```
let permissions = ["email", "public_profile"];
FBLoginManager.loginWithPermissions(
    permissions, (err, data) => this.facebookLoginCallback(err, data));
```

the call succeeds. On Android I get back an object with the attributes "provider", "profile", "expiration", "token".

On iOS I get back an object with the attribue "credentials", which has the attributes "tokenExpirationDate", "permissions", "userId" and "token".

Is this difference by design? Is there any way to get back the profile on iOS as well so that I can get the email, first name and last name?

**Comment by magus** [comment]
The APIs are different at the moment, unfortunately. You can always make a graph api request for just the profile using the returned token.

**Comment by vvkaghera** [comment]
Hello,
Can anyone help me with the same issue in iOS?

In my case...
My Login request is:


`  fetchFBUser = () => {
    let _this = this;
  FBLoginManager.setLoginBehavior(FBLoginManager.LoginBehaviors.Native);

    FBLoginManager.logout(function (error, data) {
      if (!error) {
        
        FBLoginManager.loginWithPermissions(["email", "public_profile"], function (error, data) {
          console.warn('error ' + JSON.stringify(error));

          if (!error) {
            //_this.fetchUser(data, 'facebook');
            
            var profile = JSON.parse(data.profile);
            if (profile.hasOwnProperty('email')) {
              _this.setState({
                fbEmail: profile.email
              });
            }
            _this.setState({
              gender: profile.gender,
              firstName: profile.first_name,
              lastName: profile.last_name,
              fbId: profile.id,
            })
           
          }
          else {
            console.log("error:" + JSON.stringify(error));
            window.alert("Something went wrong. Please try again.");
           
          }
        });
      } else {
        console.log(error, data);
        
      }
    });
  }`

**-------------------------------------**
**Responce :** 

>See  below:  (`  var profile = JSON.parse(data.profile);`  I am not getting **Profile** from **data** object.)
**-------------------------------------**



`{
"declinedPermissions":[
],
"credentials":{
"token":"EAAbqzmhhKsdfsfsdf84LplIRn6C1gPvQwAlUzTXcHeaKzFPlZAvBlucfaCbPLI0LOMLZCdp2OcKiP8zbLNsOEeHKHdVPbyw8gkZCvnjaEsFIkczGUvhTRl2IH6pgJjzPDZAe0ScXwbAoQZBY9mpw74QeICYFbHK5JYrEZApDw4ZCv3wmQJ1AHoLtHPhZBBB2SBUbqsVli1FRwZDZD",
"userId":"555550758130448",
"permissions":[
"email",
"public_profile"
],
"tokenExpirationDate":"2018-02-19T14:38:28+05:30"
},
"missingPermissions":[
]
}`



In `  var profile = JSON.parse(data.profile);`  I am not getting **Profile** from **data** object.

![simulator screen shot - iphone 6 - 2017-12-21 at 20 12 15](https://user-images.githubusercontent.com/10125716/34260409-db65dea2-e68b-11e7-92e7-8b8dee42ef0b.png)
