### ISSUE TITLE
Step 3 for Android missing instructions

### ISSUE THREAD

**Issue by niftylettuce** [magus/react-native-facebook-login#79]
Just thought I'd share, I found this the other day:

https://github.com/magus/react-native-facebook-login/blob/master/android/README.md#step-3---register-react-package-and-handle-onactivityresult

Should have something like this, no?

```java
    @Override
    public void onActivityResult(final int requestCode, final int resultCode, final Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        // handle onActivityResult
        mFacebookLoginPackage.handleActivityResult(requestCode, resultCode, data);
    }
```

**Comment by niftylettuce** [comment]
This actually seems to fix it, as long as documentation is up to date.  https://github.com/magus/react-native-facebook-login/pull/78

**Comment by Sh3rawi** [comment]
You do not need this in the new layout of the ReactActivity in Java. What RN version do you use?

**Comment by lwhiteley** [comment]
yes that step is important, it is not a react step, but a step that the facebook api needs to report back data to itself from the UI

**Comment by niftylettuce** [comment]
0.18.1

**Comment by iamuros** [comment]
Anyone having trouble with registering the module?

It's telling me `Cannot read property 'getCurrentToken' of undefined` which means that the module is not registered. Added @niftylettuce step but with no help.

Also tried this [[Android] Native module is not registered](https://github.com/facebook/react-native/issues/3515) and it didn't help me.

Any thoughts? @lwhiteley @Sh3rawi @niftylettuce

**Comment by whokilledtheelectricmonk** [comment]
I just linked it to RN 0.19. 

I followed these instructions: https://github.com/magus/react-native-facebook-login/blob/master/android/README.md

I also added this part to MainActivity.java (actually already had it added in for another package):

```java
@Override
    public void onActivityResult(final int requestCode, final int resultCode, final Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
    }
```

**Comment by iamuros** [comment]
Yes! That part is what i needed. Thanks @whokilledtheelectricmonk!

Don't forget guys to add `import android.content.Intent`

**Comment by niftylettuce** [comment]
Sorry I forgot to chime back in here, glad you guys got it.

**Comment by whokilledtheelectricmonk** [comment]
@iamuros Good catch, I'm adding that import to the instructions update PR

**Comment by Sh3rawi** [comment]
This is weird, the onActivityResult part is now inside the FaceBookLoginModule.java (part of the changes made for RN0.18) and ideally you shouldnt have to do it, im using this and i did not add this part to my MainActivity.java file and everything is working fine.
