### ISSUE TITLE
OnLoginFound not triggering on Android

### ISSUE THREAD

**Issue by hiei189** [magus/react-native-facebook-login#81]
Here is the component and the full project is on my repository.

```
<FBLogin
          permissions={["email","user_friends"]}
          onLogin={function(e){console.log(e)}}
          onLogout={function(e){console.log(e)}}
          onLoginFound = {function(e){alert(e)}}
          onCancel={function(e){console.log(e)}}
          onPermissionsMissing={function(e){console.log(e)}}
          onLoginNotFound={function(){console.log("No user logged in.")}}
        />
```

onLoginFound is not being triggered under any circumstance. 
But the button recognizes that an account has been already logged in, though.

**Comment by JonatanGarciaClavo** [comment]
@hiei189 I have exactly same problem, anyone fix it in another way? Could someone help us?

**Comment by hiei189** [comment]
What I did was to save the token myself when the user logged in, using AsyncStorage. Then, in the next session, try to get the token before rendering the button.

**Comment by JonatanGarciaClavo** [comment]
@hiei189 so, you save all Facebook login data and then you check it from AsyncStorage. If you have it, you assume that user it is logged it, but what happens if that user deleted access of your app? How do you check that?
BTW Regards for quick answer.

**Comment by hiei189** [comment]
You have a callback available when the user logs out, you can erase the data when that happens or save something like "KEYUserLoggedOut18022016" in the same AsyncStorage variable. 

The problem i'm seeing with this is that if the user doesn't use the app for 60 days the token would expire. Your code should able to handle that case, maybe doing a graph request when the user opens the app.

**Comment by JonatanGarciaClavo** [comment]
@hiei189 ok, thanks a lot.

**Comment by apastel** [comment]
I have this issue as well, and I'm commenting here so I can return to this later and possibly implement this workaround.

**Comment by weixingsun** [comment]
I'm facing the same problem on my Android 4.3 , too.  the FBLogin shows that "Logout from Facebook", but actually the function of onLoginFound is not invoked at all. 
Looking for fixing this, Thanks

**Comment by lwhiteley** [comment]
can someone here volunteer to test the mentioned PR
and see if this issue is properly resolved for Android

Please continue the conversation in the Pull Request 

https://github.com/magus/react-native-facebook-login/pull/105

[install from my fork directly to test (using github url)]

please see the updated docs on to reference changes for your issue. 
If not there please suggest it in the PR

**Comment by leoabacade** [comment]
same issue here 
react-native 0.24
Nexus 6 - 5.0.1
"name": "react-native-facebook-login",
"version": "1.0.3",

**Comment by lwhiteley** [comment]
can you upgrade to the latest version of this plugin.. tht is an old version without the fix

**Comment by waleedarshad-vf** [comment]
+1
