### ISSUE TITLE
Detect first time login

### ISSUE THREAD

**Issue by qasimalbaqali** [magus/react-native-facebook-login#83]
How can I detect if this is the first time a user is logging in with my app using Facebook login?

**Comment by MosesEsan** [comment]
+1

**Comment by wub** [comment]
You can use the `onLoginFound` method:

`<FBLogin onLoginFound={(data) => { console.log(data); }} />`

**Comment by qasimalbaqali** [comment]
@wub That doesn't detect the first time log in. onLogInFound actually detects if the user is already logged in through Facebook in the react-native app. 
The exact thing that I need is to detect the first time a user has clicked on the Log in with Facebook and the first time he registers on my facebook app.

**Comment by wub** [comment]
@qasimalbaqali Ah, sorry! In that case, I imagine you'd just check if the FBID exists in your database, and if not, create a record with that FBID. This package doesn't do that for you.

**Comment by ryandury** [comment]
Use some very rudimentary data persistence, which I imagine one would be doing if you're requiring login.   Just mark off a 'hasLoggedIn' boolean in your datastore..

**Comment by magus** [comment]
The credentials passed back might have a date you can use to deduce this information. It wasn't a detail I considered when writing this initially. The scenario is the app didn't have permissions and you set the permissions. A user can essentially make a login look like the first time by deleting their app settings on Facebook as well. Perhaps some local storage, or state stored on a server for your app, like suggested above, is the most direct solution.
