### ISSUE TITLE
Trying to resize FBLoginMock button - fallback to FBLoginMock neither worked

### ISSUE THREAD

**Issue by yanivkalfa** [magus/react-native-facebook-login#93]
I have tried using FBLogin and resize the width of the button to the size of the screen by setting alignSelf: 'stretch' that did nothing and the size stayed the same, - However when clicking the button it function correctly.

I then tried the same with FBLoginMock which worked i did manage to make the button as big as i wanted it however clicking the button does nothing

Whats going on ? why is FBLoginMock does nothing?

**Comment by magus** [comment]
Did you also copy over the FBLoginManager functionality from the LoginMock example? You might want to share your code because the example button should work as is from the example project.
