### ISSUE TITLE
using Linking / LinkingIOS

### ISSUE THREAD

**Issue by vanBrunneren** [magus/react-native-facebook-login#94]
I'm trying to use your plugin with the RN LinkingIOS (or newer Linking) function. The problem is both plugins use the objective-c function openURL: and I don't have a plan how to use both plugins at the same time. Do you have an idea how to get rid of this?

thanks for any advice

**Comment by Sh3rawi** [comment]
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation
{
    NSString *strURL = [url absoluteString];

    if ([strURL hasPrefix:@"sabri"]) {
      return [RCTLinkingManager application:application openURL:url
                        sourceApplication:sourceApplication annotation:annotation];
    }

    return [
      [FBSDKApplicationDelegate sharedInstance] application:application
          openURL:url
          sourceApplication:sourceApplication
          annotation:annotation
    ];
}

where "sabri" should be replaced by your url scheme.

**Comment by vanBrunneren** [comment]
wow works perfectly
thank you very much :beers:

**Comment by digital-flowers** [comment]
I think it's better to use the solution from the facebook sdk documentation:

```
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url 
    sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {

  BOOL handledFB = [[FBSDKApplicationDelegate sharedInstance] application:application
    openURL:url
    sourceApplication:sourceApplication
    annotation:annotation
  ];

  BOOL handledRCT = [RCTLinkingManager application:application openURL:url sourceApplication:sourceApplication annotation:annotation];

  return handledFB || handledRCT;
}
```
