### ISSUE TITLE
Not redirecting to application after login on iOS 9.0.2

### ISSUE THREAD

**Issue by GuillaumeNachury** [magus/react-native-facebook-login#96]
Hi,
When calling the ``` FBLoginManager.loginWithPermissions() ``` method I got the Safari screen that pops up but after the user log in and accept the permission the Safaris screen stays empty and the user is not redirected to my application.

I added the LSApplicationQueriesSchemes entries to my plist file

![image](https://cloud.githubusercontent.com/assets/617536/13432181/d790d6dc-dfcc-11e5-9281-aa61799fdd63.png)

Is there any extra data to set in order to get the redirection working the iOS 9.x ?

Thx

**Comment by yonahforst** [comment]
@GuillaumeNachury I'm having the same problem. did you manage to resolve it?

**Comment by yonahforst** [comment]
ok, i solved it. I had forgotten to connect the app delegate: https://github.com/magus/react-native-facebook-login#appdelegatem-modifications
